export const ICEBREAKER_PROMPTS = [
  'What is a meal you always associate with home?',
  'Who would you invite to your dream dinner?',
  'What song instantly changes your mood?',
  'What is a tiny thing that made your week better?',
  'Which place in Egypt do you want to visit next?',
  'What is a skill you secretly want to learn?',
  'What is your safest comfort movie?',
  'What was your funniest school memory?',
  'Which friend gives the best advice?',
  'What is your perfect Friday plan?',
  'What is a smell that brings back a memory?',
  'What is something you changed your mind about?',
  'What is your favorite late-night snack?',
  'Which app would be hardest for you to delete?',
  'What is a small tradition you love?',
  'What is one thing you are unusually good at?',
  'What is a place that feels peaceful to you?',
  'Which fictional world would you visit?',
  'What is a compliment you still remember?',
  'What is your most chaotic travel story?',
  'What is a food you disliked as a kid but like now?',
  'Who in the group is most likely to plan a trip?',
  'What is a habit that makes your day smoother?',
  'What is your favorite family saying?',
  'What is something you would teach a younger cousin?',
  'Which game did you play most as a child?',
  'What is a random fact you love?',
  'What is a moment that made you feel brave?',
  'What is the best gift you ever received?',
  'What is a song everyone should hear once?',
  'What is your favorite thing about gatherings?',
  'What is one place you know like the back of your hand?',
  'What is a dream you had as a child?',
  'Which person makes you laugh fastest?',
  'What is your favorite rainy-day activity?',
  'What is something you wish people asked you more often?',
  'What is a small win you are proud of?',
  'What is your favorite street food?',
  'What is a topic you could talk about for hours?',
  'What is something kind someone did for you recently?',
  'What is a memory tied to a specific song?',
  'What is your favorite way to celebrate?',
  'Who was your first favorite teacher?',
  'What is one thing that always feels worth the effort?',
  'What is a rule you would add to every gathering?',
  'Which city has the best energy for you?',
  'What is a simple pleasure you refuse to give up?',
  'What is a story your family repeats about you?',
  'What is something you want to do before the year ends?',
  'What is your favorite question to ask new people?',
];
