import type { TranslationSchema } from './en';

export const ar: TranslationSchema = {
  common: {
    appName: 'لمة',
    continue: 'متابعة',
    next: 'التالي',
    back: 'رجوع',
    cancel: 'إلغاء',
    save: 'حفظ',
    done: 'تم',
    seeAll: 'عرض الكل',
    retry: 'حاول مجددًا',
    loading: 'جارٍ التحميل…',
    signIn: 'تسجيل الدخول',
    edit: 'تعديل',
    copy: 'نسخ',
    copied: 'تم النسخ!',
    share: 'مشاركة',
  },
  errors: {
    unexpectedTitle: 'حدث خطأ في لمّة',
    unexpectedMessage: 'خططك محفوظة. حاول مجددًا للعودة إلى لمّتك.',
  },
  tabs: {
    home: 'الرئيسية',
    discover: 'استكشف',
    create: 'إنشاء',
    games: 'الألعاب',
    notifications: 'الإشعارات',
    profile: 'حسابي',
  },
  onboarding: {
    slide1Title: 'اصنع لمات جميلة.',
    slide1Subtitle: 'ادعُ الجميع واعرف من سيحضر.',
    slide2Title: 'لحظات مميزة مع أحبابك',
    slide2Subtitle: 'أعياد الميلاد والأفراح وكل ما بينهما.',
    slide3Title: 'أماكن جديدة. ذكريات أجمل.',
    slide3Subtitle: 'خطّط للرحلات واللمات في كل أنحاء مصر.',
    slide4Title: 'أكل طيب. ناس أحلى.',
    slide4Subtitle: 'اجمع الجميع حول المائدة.',
    tagline: 'ناس · مناسبات · مصر أحلى مع بعض',
    skip: 'تخطي',
    getStarted: 'ابدأ الآن',
  },
  auth: {
    welcomeTitle: 'أهلًا بك في لمة',
    welcomeSubtitle: 'خطّط، ادعُ، واحتفل مع بعض.',
    continueAsGuest: 'المتابعة كضيف',
    continueWithGoogle: 'المتابعة عبر جوجل',
    continueWithApple: 'المتابعة عبر آبل',
    or: 'أو',
    noPhoneTitle: 'بدون رقم هاتف. بدون رموز SMS.',
    noPhoneSubtitle: 'نشاطك كضيف يبقى معك عند ترقية حسابك.',
    signingIn: 'جارٍ تسجيل الدخول…',
    errorGeneric: 'تعذّر تسجيل الدخول. حاول مجددًا.',
    errorPlayServices:
      'خدمات Google Play مطلوبة. ثبّتها من متجر Play ثم حاول مرة أخرى.',
  },
  home: {
    greeting: 'مساء الخير،',
    upcoming: 'القادمة',
    hosting: 'أستضيفها',
    past: 'السابقة',
    yourEvents: 'مناسباتك',
    youreGoing: 'أنت ذاهب',
    going: 'ذاهب',
    createEvent: 'أنشئ مناسبة',
    emptyUpcomingTitle: 'لا توجد مناسبات قادمة بعد',
    emptyUpcomingMessage: 'أنشئ أول لمة وادعُ أحبابك.',
    emptyHostingTitle: 'لا تستضيف أي مناسبة',
    emptyHostingMessage: 'ابدأ التخطيط واجمع الجميع.',
    emptyPastTitle: 'لا توجد مناسبات سابقة',
    emptyPastMessage: 'ستظهر ذكرياتك هنا.',
  },
  event: {
    youAreHosting: 'أنت المضيف',
    shareInvite: 'شارك الدعوة',
    manageGuests: 'قائمة الضيوف',
    notFoundTitle: 'المناسبة غير موجودة',
    notFoundMessage: 'ممكن يكون رابط الدعوة غلط أو المناسبة اتشالت.',
    hostedBy: 'يستضيفها',
    contactHost: 'تواصل مع المضيف',
    openInMaps: 'افتح في الخرائط',
    going: 'ذاهب',
    maybe: 'ربما',
    cantGo: 'لا أستطيع',
    peopleGoing: '{{count}} شخص ذاهب',
    onePersonGoing: 'شخص واحد ذاهب',
    eventUpdates: 'تحديثات المناسبة',
    pinned: 'مثبّت',
    guestList: 'قائمة المدعوين',
    hosts: 'المضيفون',
    family: 'العائلة',
    friends: 'الأصدقاء',
    declined: 'اعتذروا',
    eventCreator: 'منشئ المناسبة',
    reminderDayTitle: '{{title}} غدًا',
    reminderDayBody: '{{when}} · {{place}}',
    reminderHourTitle: '{{title}} تبدأ خلال ساعة',
    reminderHourBody: '{{place}}',
    coHost: 'مضيف مشارك',
  },
  create: {
    title: 'إنشاء مناسبة',
    stepBasics: 'الأساسيات',
    stepDetails: 'التفاصيل',
    stepLocation: 'الموقع',
    stepInvite: 'الدعوة',
    eventTitle: 'اسم المناسبة',
    eventTitlePlaceholder: 'مثال: عشاء عيد ميلاد مصطفى',
    category: 'الفئة',
    categoryHint: 'اختر الفئة الأنسب لمناسبتك',
    description: 'الوصف',
    descriptionPlaceholder: 'أخبر ضيوفك بما يمكن توقعه…',
    livePreview: 'معاينة حية للدعوة',
    livePreviewHint: 'هكذا ستظهر مناسبتك',
    when: 'متى',
    whenHint: 'حدد تاريخ ووقت مناسبتك',
    where: 'أين',
    whereHint: 'أضف موقع مناسبتك',
    date: 'التاريخ',
    startTime: 'وقت البدء',
    endTime: 'وقت الانتهاء',
    venueName: 'اسم المكان',
    areaAddress: 'المنطقة / العنوان',
    useCurrentLocation: 'استخدم موقعي الحالي',
    pickOnMap: 'اختر الموقع على الخريطة',
    chooseLocation: 'اختر موقعًا',
    confirmLocation: 'تأكيد الموقع',
    searchLocation: 'ابحث عن مكان أو عنوان',
    locationHint: 'اكتب 3 أحرف على الأقل للبحث في OpenStreetMap',
    locationNoResults: 'لم يتم العثور على أماكن. جرّب بحثًا مختلفًا.',
    locationError: 'تعذّر البحث الآن. تحقق من اتصالك.',
    locationConfirmError: 'تعذّر تحديد هذا الموقع. حرّك العلامة وحاول مجددًا.',
    mapUnavailable:
      'تعذّر تحميل الخريطة. تحقق من إعداد مفتاح Google Maps في التطبيق الأصلي.',
    chooseTheme: 'اختر تصميمًا',
    customTheme: 'مخصص',
    themes: 'التصاميم',
    useThisTheme: 'استخدم هذا التصميم',
    preview: 'معاينة',
    publish: 'نشر المناسبة',
    draftSaved: 'تم حفظ المسودة',
    whenWhere: 'متى وأين',
    stepProgress: 'الخطوة {{current}} من {{total}}',
    selectDate: 'اختر التاريخ',
    selectTime: 'اختر الوقت',
    dateTBD: 'التاريخ والوقت',
    locationTBD: 'الموقع',
    visibility: 'الظهور',
    visibilityPublic: 'مناسبة عامة',
    visibilityPrivate: 'مناسبة خاصة',
    visibilityPublicHint: 'أي شخص لديه الرابط يمكنه الرؤية والانضمام',
    visibilityPrivateHint: 'فقط المدعوون يمكنهم رؤية هذه المناسبة',
    published: 'مناسبتك أصبحت جاهزة!',
    publishing: 'جارٍ النشر…',
    publishError: 'تعذّر نشر المناسبة. مسودتك محفوظة—حاول مرة أخرى.',
    storageUnauthorized: 'تعذّر رفع صورة الغلاف. مسودتك محفوظة—حاول مرة أخرى.',
    discardTitle: 'تجاهل هذه المسودة؟',
    discardMessage: 'سيتم فقدان تقدمك في هذه المناسبة.',
    discard: 'تجاهل',
    keepEditing: 'متابعة التعديل',
    errorTitleRequired: 'أضف اسمًا لمناسبتك',
    errorTitleTooLong: 'الاسم طويل جدًا',
    errorDescriptionTooLong: 'الوصف طويل جدًا',
    errorCategoryRequired: 'اختر فئة',
    errorDateRequired: 'اختر التاريخ والوقت',
    errorEndBeforeStart: 'وقت الانتهاء يجب أن يكون بعد البدء',
    errorVenueRequired: 'أضف اسم المكان',
    errorAddressRequired: 'أضف المنطقة أو العنوان',
  },
  drafts: {
    title: 'مسوداتي',
    subtitle: 'أكمل تجهيز مناسباتك',
    emptyTitle: 'لا توجد مسودات بعد',
    emptyMessage: 'ابدأ إنشاء مناسبة وسيتم حفظها هنا.',
    lastEdited: 'آخر تعديل {{when}}',
    untitled: 'مناسبة بدون عنوان',
    delete: 'حذف',
    resume: 'متابعة',
  },
  themeNames: {
    wedding: 'أنيق',
    birthday: 'احتفال',
    dinner: 'عشاء',
    travel: 'سفر',
    generic: 'بسيط',
  },
  categories: {
    birthday: 'عيد ميلاد',
    wedding: 'زفاف',
    engagement: 'خطوبة',
    dinner: 'عشاء',
    trip: 'رحلة',
    gathering: 'لمة',
    iftar: 'إفطار',
    other: 'أخرى',
  },
  share: {
    title: 'مشاركة الدعوة',
    tagline: 'انشر المحبة · اجمع الناس',
    whatsapp: 'واتساب',
    copyLink: 'نسخ الرابط',
    messagePreview: 'معاينة رسالة الدعوة',
    invitedTo: 'أنت مدعو إلى {{title}}',
    shareError: 'تعذّر فتح قائمة المشاركة. حاول مرة أخرى.',
    footer: 'مع بعض · مصر أحلى',
  },
  discover: {
    all: 'الكل',
    title: 'استكشف',
    subtitle: 'اكتشف المناسبات العامة القريبة منك',
    searchPlaceholder: 'ابحث عن مناسبات أو مضيفين أو أماكن',
    trending: 'الأكثر رواجًا',
    categories: 'تصفح حسب الفئة',
    nearby: 'يحدث في مصر',
    emptyTitle: 'لا توجد مناسبات',
    emptyMessage: 'جرّب بحثًا أو فئة مختلفة.',
  },
  games: {
    title: 'الألعاب',
    subtitle: 'اختر لعبة، افتح غرفة، والعبوا معًا على أجهزة الجميع.',
    playersRange: '{{min}}–{{max}} لاعبين',
    hostAuthoritative: 'مزامنة بقيادة المضيف',
    joinRoom: 'الانضمام إلى غرفة',
    playerName: 'اسم اللاعب',
    joinGame: 'انضم للعبة',
    joinCodeRequired: 'أدخل رمز الغرفة.',
    joinCodeNotFound: 'لا توجد غرفة بهذا الرمز.',
    availableRooms: 'الغرف المتاحة',
    roomSummary: '{{code}} · {{count}} متصل',
    roomCode: 'رمز الغرفة',
    sharedSessionHint:
      'شارك الرابط أو الرمز مع أصحابك. يقدروا ينضموا من أي مكان، مش لازم نفس شبكة الواي فاي.',
    copyCode: 'نسخ الرمز',
    codeCopied: 'تم النسخ!',
    shareInvite: 'مشاركة الدعوة',
    shareRoomMessage:
      'انضم للعبة {{game}} معايا على لمّة! اضغط للفتح: {{link}}\nأو اكتب رمز الغرفة {{code}} في الألعاب.',
    joiningRoom: 'جارٍ الانضمام للغرفة {{code}}…',
    inviteExpired: 'الغرفة {{code}} انتهت أو غير موجودة. اطلب من المضيف رابط جديد.',
    players: 'اللاعبون',
    host: 'المضيف',
    disconnected: 'غير متصل',
    startGame: 'بدء اللعبة',
    inGame: 'بدأت اللعبة',
    leaveLobby: 'مغادرة الغرفة',
    triviaSetup: 'إعداد تريفيا تايم',
    triviaPack: 'الحزمة: {{pack}}',
    triviaQuestions: '{{count}} أسئلة · {{seconds}} ثانية لكل سؤال',
    triviaPrizeHint: 'نص الجائزة يظهر قبل الجولة وللفائز في النهاية.',
    choosePack: 'اختر الحزمة',
    questionCount: 'عدد الأسئلة',
    timePerQuestion: 'وقت كل سؤال',
    secondsShort: '{{seconds}}ث',
    prize: 'الجائزة',
    prizePlaceholder: 'الفائز يختار قائمة التشغيل التالية',
    yourSecretRole: 'دورك السري',
    noRoleYet: 'لا يوجد دور بعد',
    revealVote: 'كشف التصويت',
    nextPhase: 'المرحلة التالية',
    triviaQuestionProgress: 'السؤال {{current}}/{{total}}',
    triviaTimer: '{{seconds}}ث',
    revealAnswer: 'إظهار الإجابة',
    nextQuestion: 'السؤال التالي',
    leaderboard: 'الترتيب',
    triviaWinner: '{{name}} فاز',
    triviaPrizeAward: 'الجائزة: {{prize}}',
    roundNumber: 'الجولة {{round}}',
    noPlayer: 'لا يوجد لاعب',
    noPrompt: 'لا يوجد سؤال جاهز',
    icebreakerPromptPrivate: 'السؤال ظاهر على جهازه فقط.',
    nextPrompt: 'السؤال التالي',
    icebreakersSetup: 'إعداد كاسرات الجليد',
    icebreakersPromptCount: '{{count}} سؤالًا جاهزًا',
    icebreakersRotation: 'الأدوار تدور بعدل قبل تكرار أي لاعب.',
    quarterMileSetup: 'إعداد ربع ميل',
    quarterMileChooseCategory: 'اختار الفئة',
    quarterMilePackLine: '{{pack}} · {{count}} اختيار',
    quarterMileHint: 'كل دور بيظهرلك اختيار واحد وفيه اختيار مخفي. خد اللي قدامك أو غامر بالمخفي. أقوى فريق يكسب.',
    quarterMileKnown: 'اللي قدامك',
    quarterMileHidden: 'الاختيار المخفي',
    quarterMileTake: 'خدها',
    quarterMileLeave: 'سيبها (خد المخفية)',
    quarterMileYourGarage: 'فريقك',
    quarterMileScores: 'نتيجة الفرق',
    quarterMileWinner: '{{name}} كسب!',
    quarterMileWaiting: 'مستنين {{name}} يختار…',
    quarterMileRevealPair: '{{name}} اختار {{choice}}',
    quarterMileChoiceTake: 'اللي قدامه',
    quarterMileChoiceLeave: 'المخفي',
    needPlayers: 'محتاجين {{count}} لاعبين على الأقل للبدء (موجود دلوقتي {{have}}).',
    waitingForHostStart: 'مستنيين الهوست يبدأ اللعبة…',
    waitingForHost: 'مستنيين الهوست…',
    lateJoinerTitle: 'اللعبة شغالة بالفعل',
    lateJoinerMessage: 'دخلت بعد ما الجولة بدأت. هتدخل معانا أول ما الهوست يبدأ الجولة الجاية.',
    spectatorQuarterMile: 'ربع ميل تحدي بين لاعبين اتنين. إنت بتتفرج على الجولة دي.',
    playAgain: 'العب تاني',
    actionFailed: 'ماوصلش. اتأكد من النت وجرب تاني.',
    actionFailedTitle: 'ماتبعتش',
    triviaTimeLeft: 'باقي {{seconds}} ثانية',
    triviaAnswered: '{{count}}/{{total}} جاوبوا',
    triviaYouAnswered: 'إجابتك اتسجلت. مستنيين الباقي…',
    icebreakerYourTurn: 'دورك! جاوب بصوت عالي وبعدين دوس خلصت.',
    icebreakerDone: 'خلصت، اللي بعدي',
    icebreakerWaiting: '{{name}} بيجاوب…',
    imposterSetup: 'إزاي تلعب مين الدخيل',
    imposterRule1: 'الكل بياخد نفس الكلمة السرية، إلا دخيل واحد بيتختار عشوائي وبيشوف الفئة بس.',
    imposterRule2: 'كل واحد بدوره يقول تلميح قصير عن الكلمة. من غير ما يفضحها!',
    imposterRule3: 'الكل يصوّت من موبايله على اللي فاكره الدخيل.',
    imposterRule4: 'لو اتمسك الدخيل ليه فرصة أخيرة يخمن الكلمة. التعادل أو التصويت الغلط يعني الدخيل كسب.',
    imposterRound: 'الجولة {{round}}',
    imposterCategory: 'الفئة: {{category}}',
    imposterYourWord: 'كلمتك السرية',
    imposterYouAre: 'إنت الدخيل',
    imposterYouAreHint: 'اندمج معاهم. اسمع التلميحات وخمن الكلمة من غير ما حد ياخد باله.',
    imposterNotIn: 'بتتفرج على الجولة دي',
    imposterCluesTitle: 'وقت التلميحات — ترتيب الكلام',
    imposterCluesHint: 'كل لاعب يقول تلميح قصير بصوت عالي بالترتيب ده. وبعدين الهوست يفتح التصويت.',
    imposterStartVote: 'افتح التصويت',
    imposterVoteTitle: 'مين الدخيل؟',
    imposterVoted: 'صوتك اتبعت. مستنيين الكل… ({{count}}/{{total}})',
    imposterRevealVotes: 'اكشف الأصوات دلوقتي',
    imposterGuessTitle: '{{name}} اتمسك! فرصة أخيرة يخمن الكلمة.',
    imposterGuessYou: 'اتمسكت! خمن الكلمة السرية عشان تسرق الفوز:',
    imposterGuessWaiting: '{{name}} بيخمن الكلمة…',
    imposterSkipGuess: 'تخطي التخمين',
    imposterPlayersWin: 'اللاعبين كسبوا! الدخيل كان {{name}}.',
    imposterWins: 'الدخيل كسب! كان {{name}}.',
    imposterTie: 'التصويت اتعادل، محدش خرج.',
    imposterWrongOut: '{{name}} خرج بالتصويت، بس كان بريء.',
    imposterGuessedRight: '{{name}} خمن الكلمة صح.',
    imposterGuessedWrong: '{{name}} خمن غلط.',
    imposterWordWas: 'الكلمة كانت: {{word}}',
    imposterVotesFor: '{{name}}: {{count}} صوت',
    imposterVotesFor_one: '{{name}}: صوت واحد',
    imposterVotesFor_other: '{{name}}: {{count}} صوت',
    imposterScores: 'النقط',
    imposterNextRound: 'الجولة الجاية',
    quarterMileNextPair: 'الزوج التالي',
    loadingContentTitle: 'جارٍ تحميل الألعاب',
    loadingContentMessage: 'نحمّل أحدث القواعد والأسئلة والأسئلة التعارفية.',
    contentErrorTitle: 'تعذر تحميل الألعاب',
    contentErrorMessage:
      'تحقق من الاتصال وحاول مرة أخرى. الألعاب التي تم تحميلها سابقًا تبقى محفوظة على هذا الجهاز.',
    contentEmptyTitle: 'لا توجد ألعاب متاحة',
    contentEmptyMessage:
      'أضف بيانات مجموعة الألعاب قبل استضافة غرفة من هذا الجهاز.',
    retry: 'حاول مرة أخرى',
  },
  notifications: {
    title: 'الإشعارات',
    subtitle: 'ابقَ على تواصل مع أحبابك',
    markAllRead: 'تعليم الكل كمقروء',
    today: 'اليوم',
    earlier: 'سابقًا',
    emptyTitle: 'لا يوجد جديد',
    emptyMessage: 'ستظهر الدعوات والردود والتحديثات هنا.',
  },
  profile: {
    title: 'الملف والإعدادات',
    subtitle: 'مناسباتك. مجتمعك. لمتك.',
    hostedEvents: 'استضاف {{count}} مناسبة',
    oneHostedEvent: 'استضاف مناسبة واحدة',
    joined: 'انضم إلى {{count}}',
    language: 'اللغة',
    notifications: 'الإشعارات',
    notificationsHint: 'تذكيرات وتحديثات المناسبات والمزيد',
    appearance: 'المظهر',
    lightMode: 'الوضع الفاتح',
    darkMode: 'الوضع الداكن',
    myDrafts: 'مسوداتي',
    myDraftsHint: 'أكمل تجهيز مناسباتك',
    help: 'المساعدة والدعم',
    helpHint: 'الأسئلة الشائعة والتواصل والمزيد',
    signOut: 'تسجيل الخروج',
    signOutHint: 'إلى اللقاء!',
    guest: 'ضيف',
    upgradePrompt: 'سجّل الدخول لحفظ مناسباتك',
    editProfileTitle: 'تعديل الملف الشخصي',
    displayNameLabel: 'الاسم الظاهر',
    displayNamePlaceholder: 'اسمك',
    profileSaved: 'تم تحديث الملف الشخصي',
    upgradeTitle: 'سجّل الدخول إلى لمّة',
    upgradeSubtitle: 'احتفظ بمناسباتك ومسوداتك وردودك على جميع أجهزتك.',
  },
  language: {
    title: 'اللغة',
    english: 'English',
    arabic: 'العربية',
    restartHint: 'يُعاد تشغيل التطبيق لتطبيق اللغة واتجاه الواجهة.',
  },
  settings: {
    defaultBio: 'ناس طيبين. أيام أحلى.',
    editProfile: 'تعديل الملف',
    notificationsTitle: 'الإشعارات',
    remindersLabel: 'تذكيرات المناسبات',
    remindersHint: 'احصل على تذكير قبل بدء المناسبات',
    rsvpsLabel: 'تحديثات الردود',
    rsvpsHint: 'عندما يرد ضيوفك على مناسباتك',
    updatesLabel: 'تحديثات المناسبة',
    updatesHint: 'المنشورات والتغييرات من المضيفين',
    invitesLabel: 'الدعوات الجديدة',
    invitesHint: 'عندما يدعوك أحدهم',
    appearanceTitle: 'المظهر',
    appearanceHint: 'اختر شكل لمة',
    light: 'الوضع الفاتح',
    dark: 'الوضع الداكن',
    system: 'حسب النظام',
    helpTitle: 'المساعدة والدعم',
    faq: 'الأسئلة الشائعة',
    contactUs: 'تواصل معنا',
    terms: 'شروط الخدمة',
    privacy: 'سياسة الخصوصية',
    appVersion: 'لمة الإصدار {{version}}',
  },
  guests: {
    summaryGoing: '{{count}} حاضر',
    summaryMaybe: '{{count}} ربما',
    summaryDeclined: '{{count}} اعتذر',
    emptyGoingTitle: 'لا يوجد حضور بعد',
    emptyGoingMessage: 'شارك الدعوة ليتمكن ضيوفك من الرد.',
    emptyMaybeTitle: 'لا توجد ردود "ربما" بعد',
    emptyMaybeMessage: 'سيظهر هنا الضيوف الذين يردون بـ "ربما".',
    emptyDeclinedTitle: 'لم يعتذر أحد',
    emptyDeclinedMessage: 'سيظهر هنا الضيوف الذين لا يستطيعون الحضور.',
  },
  profileSetup: {
    title: 'جهّز ملفك الشخصي',
    subtitle:
      'أضف اسمك وصورة ليعرفك أصدقاؤك. يمكنك التخطي وإكمال ذلك لاحقاً.',
    addPhoto: 'أضف صورة',
    changePhoto: 'غيّر الصورة',
    removePhoto: 'إزالة',
    save: 'احفظ وتابع',
    skip: 'تخطَّ الآن',
    photoError: 'تعذر فتح الصور. حاول مرة أخرى.',
    saveError: 'تعذر حفظ ملفك الشخصي. تحقق من الاتصال وحاول مرة أخرى.',
  },
  info: {
    sectionTitle: 'عن لمّة',
    aboutTitle: 'عن لمّة',
    aboutHint: 'ما هي لمّة ومن يصنعها',
    contactTitle: 'تواصل معنا',
    contactHint: 'أسئلة أو اقتراحات أو دعم',
    termsTitle: 'شروط الخدمة',
    termsHint: 'قواعد استخدام لمّة',
    privacyTitle: 'سياسة الخصوصية',
    privacyHint: 'ما نجمعه ولماذا',
    lastUpdated: 'آخر تحديث: سبتمبر 2026',
    openWebsite: 'افتح lamma-links.vercel.app',
    version: 'الإصدار {{version}}',
    about: {
      tagline: 'لمّ ناسك.',
      intro:
        'لمّة تساعدك على تنظيم المناسبات وجمع الأهل والأصدقاء، من أعياد الميلاد والأفراح إلى العزومات والرحلات والإفطار.',
      s1Title: 'نظّم مناسباتك',
      s1Body:
        'أنشئ مناسبة في خطوات قليلة، واختر تصميماً أو صورة غلاف خاصة بك، وشارك رابط دعوة جميلاً على واتساب أو أي مكان آخر.',
      s2Title: 'اعرف مين جاي',
      s2Body:
        'يرد الضيوف بـ "حاضر" أو "ربما" أو "لا أستطيع"، ويرى المضيف قائمة الضيوف كاملة في مكان واحد.',
      s3Title: 'العبوا مع بعض',
      s3Body:
        'ابدأ لعبة جماعية مثل الأسئلة أو المحتال أو كسر الجليد أو ربع ميل، وكل واحد يلعب من موبايله.',
      s4Title: 'صُنعت في مصر',
      s4Body: 'لمّة مصنوعة في مصر، بالعربية والإنجليزية، على طريقتنا في الاحتفال.',
    },
    contact: {
      intro:
        'يسعدنا أن نسمع منك. أرسل لنا أسئلتك أو أفكارك أو أي مشكلة وسنرد عليك في أقرب وقت.',
      emailLabel: 'البريد الإلكتروني',
      sendEmail: 'أرسل لنا بريداً إلكترونياً',
      responseTime: 'نرد عادة خلال يومين إلى ثلاثة أيام عمل.',
      reportTitle: 'الإبلاغ عن مشكلة',
      reportBody:
        'اخبرنا بما حدث، وفي أي شاشة كنت، ونوع هاتفك. لقطات الشاشة تساعدنا كثيراً.',
      emailSubject: 'دعم لمّة',
      emailError: 'لا يوجد تطبيق بريد. راسلنا على {{email}}.',
    },
    terms: {
      intro: 'باستخدامك لمّة فأنت توافق على هذه الشروط. يُرجى قراءتها بعناية.',
      s1Title: '1. استخدام لمّة',
      s1Body:
        'يمكنك استخدام لمّة كضيف أو بحساب Google أو Apple. أنت مسؤول عن النشاط على حسابك وعن تأمين جهازك.',
      s2Title: '2. المحتوى الخاص بك',
      s2Body:
        'المناسبات والصور والأسماء والرسائل التي تضيفها ملك لك. وتسمح للمّة بحفظها وعرضها لمن تشاركها معهم، فقط لتشغيل الخدمة.',
      s3Title: '3. الاستخدام المقبول',
      s3Body:
        'لا تستخدم لمّة في أي شيء غير قانوني أو مسيء أو مضلل، ولا ترفع محتوى لا تملك حق مشاركته. قد نحذف المحتوى أو نوقف الحسابات المخالفة.',
      s4Title: '4. المناسبات والدعوات',
      s4Body:
        'المضيف مسؤول عن مناسبته. أي شخص لديه رابط الدعوة يمكنه رؤية المناسبة، فشارك الروابط مع من تثق بهم فقط. لمّة لا تنظم المناسبات المنشأة في التطبيق وليست مسؤولة عنها.',
      s5Title: '5. الألعاب',
      s5Body: 'الألعاب للتسلية. أي جائزة تُذكر في لعبة يرتبها المضيف وليس لمّة.',
      s6Title: '6. توفر الخدمة',
      s6Body:
        'تُقدَّم لمّة "كما هي". نعمل على استمرار عملها لكن لا نضمن أن تكون متاحة دائماً أو خالية من الأخطاء. تُحذف المناسبات تلقائياً بعد انتهائها.',
      s7Title: '7. التغييرات',
      s7Body:
        'قد نحدّث هذه الشروط، وإذا كان التغيير مهماً سنخبرك داخل التطبيق. استمرارك في استخدام لمّة يعني موافقتك على الشروط المحدثة.',
      s8Title: '8. التواصل',
      s8Body: 'لديك سؤال عن هذه الشروط؟ راسلنا على {{email}}.',
    },
    privacy: {
      intro:
        'خصوصيتك تهمنا. توضح هذه السياسة ما تجمعه لمّة ولماذا والخيارات المتاحة لك.',
      s1Title: 'ما نجمعه',
      s1Body:
        'بيانات الحساب (معرّف مجهول للضيوف، أو اسمك وبريدك وصورتك من Google أو Apple)، والاسم والصورة التي تختارها لملفك، والمناسبات التي تنشئها وردودك عليها، ونشاط الألعاب، وبيانات أساسية عن الجهاز مثل رمز الإشعارات وإصدار التطبيق وتقارير الأعطال.',
      s2Title: 'كيف نستخدمها',
      s2Body:
        'لتشغيل التطبيق فقط: عرض مناسباتك ودعواتك، ومزامنة الردود والألعاب، وإرسال التذكيرات والإشعارات التي فعّلتها، وإصلاح الأعطال وتحسين لمّة. لا نبيع بياناتك ولا نعرض إعلانات.',
      s3Title: 'من يمكنه رؤيتها',
      s3Body:
        'تفاصيل المناسبة ظاهرة لمن لديه رابط الدعوة. اسمك وردك ظاهران لمضيف المناسبة وضيوفها. صورة ملفك تبقى في حسابك.',
      s4Title: 'مزودو الخدمة',
      s4Body:
        'تستخدم لمّة خدمات Google Firebase (تسجيل الدخول وقاعدة البيانات والإشعارات والتحليلات وتقارير الأعطال) لحفظ البيانات ومعالجتها نيابة عنا.',
      s5Title: 'الأمان',
      s5Body:
        'تُرسل البيانات عبر اتصالات مشفرة. وعلى هاتفك يُحفظ رمز جلسة الضيف في تخزين مشفر محمي بسلسلة مفاتيح الجهاز.',
      s6Title: 'خياراتك',
      s6Body:
        'يمكنك تغيير اسمك، وإيقاف الإشعارات من الإعدادات، وحذف مناسباتك، وتسجيل الخروج في أي وقت. لحذف حسابك وبياناتك راسلنا وسنقوم بذلك.',
      s7Title: 'الأطفال',
      s7Body: 'لمّة غير موجهة للأطفال دون 13 عاماً.',
      s8Title: 'التواصل',
      s8Body: 'لديك سؤال عن الخصوصية؟ راسلنا على {{email}}.',
    },
  },
};
