import type { TranslationSchema } from './en';

export const ar: TranslationSchema = {
  common: {
    appName: 'لمة',
    continue: 'متابعة',
    next: 'التالي',
    back: 'رجوع',
    cancel: 'إلغاء',
    save: 'حفظ',
    done: 'تم',
    seeAll: 'عرض الكل',
    retry: 'حاول مجددًا',
    loading: 'جارٍ التحميل…',
    signIn: 'تسجيل الدخول',
    edit: 'تعديل',
    copy: 'نسخ',
    copied: 'تم النسخ!',
    share: 'مشاركة',
  },
  tabs: {
    home: 'الرئيسية',
    discover: 'استكشف',
    create: 'إنشاء',
    notifications: 'الإشعارات',
    profile: 'حسابي',
  },
  onboarding: {
    slide1Title: 'اصنع لمات جميلة.',
    slide1Subtitle: 'ادعُ الجميع واعرف من سيحضر.',
    slide2Title: 'لحظات مميزة مع أحبابك',
    slide2Subtitle: 'أعياد الميلاد والأفراح وكل ما بينهما.',
    slide3Title: 'أماكن جديدة. ذكريات أجمل.',
    slide3Subtitle: 'خطّط للرحلات واللمات في كل أنحاء مصر.',
    slide4Title: 'أكل طيب. ناس أحلى.',
    slide4Subtitle: 'اجمع الجميع حول المائدة.',
    tagline: 'ناس · مناسبات · مصر أحلى مع بعض',
    skip: 'تخطي',
    getStarted: 'ابدأ الآن',
  },
  auth: {
    welcomeTitle: 'أهلًا بك في لمة',
    welcomeSubtitle: 'خطّط، ادعُ، واحتفل مع بعض.',
    continueAsGuest: 'المتابعة كضيف',
    continueWithGoogle: 'المتابعة عبر جوجل',
    continueWithApple: 'المتابعة عبر آبل',
    or: 'أو',
    noPhoneTitle: 'بدون رقم هاتف. بدون رموز SMS.',
    noPhoneSubtitle: 'نشاطك كضيف يبقى معك عند ترقية حسابك.',
    signingIn: 'جارٍ تسجيل الدخول…',
    errorGeneric: 'تعذّر تسجيل الدخول. حاول مجددًا.',
  },
  home: {
    greeting: 'مساء الخير،',
    upcoming: 'القادمة',
    hosting: 'أستضيفها',
    past: 'السابقة',
    yourEvents: 'مناسباتك',
    youreGoing: 'أنت ذاهب',
    going: 'ذاهب',
    createEvent: 'أنشئ مناسبة',
    emptyUpcomingTitle: 'لا توجد مناسبات قادمة بعد',
    emptyUpcomingMessage: 'أنشئ أول لمة وادعُ أحبابك.',
    emptyHostingTitle: 'لا تستضيف أي مناسبة',
    emptyHostingMessage: 'ابدأ التخطيط واجمع الجميع.',
    emptyPastTitle: 'لا توجد مناسبات سابقة',
    emptyPastMessage: 'ستظهر ذكرياتك هنا.',
  },
  event: {
    hostedBy: 'يستضيفها',
    contactHost: 'تواصل مع المضيف',
    openInMaps: 'افتح في الخرائط',
    going: 'ذاهب',
    maybe: 'ربما',
    cantGo: 'لا أستطيع',
    peopleGoing: '{{count}} شخص ذاهب',
    eventUpdates: 'تحديثات المناسبة',
    pinned: 'مثبّت',
    guestList: 'قائمة المدعوين',
    hosts: 'المضيفون',
    family: 'العائلة',
    friends: 'الأصدقاء',
    declined: 'اعتذروا',
    eventCreator: 'منشئ المناسبة',
    coHost: 'مضيف مشارك',
  },
  create: {
    title: 'إنشاء مناسبة',
    stepBasics: 'الأساسيات',
    stepDetails: 'التفاصيل',
    stepLocation: 'الموقع',
    stepInvite: 'الدعوة',
    eventTitle: 'اسم المناسبة',
    eventTitlePlaceholder: 'مثال: عشاء عيد ميلاد مصطفى',
    category: 'الفئة',
    categoryHint: 'اختر الفئة الأنسب لمناسبتك',
    description: 'الوصف',
    descriptionPlaceholder: 'أخبر ضيوفك بما يمكن توقعه…',
    livePreview: 'معاينة حية للدعوة',
    livePreviewHint: 'هكذا ستظهر مناسبتك',
    when: 'متى',
    whenHint: 'حدد تاريخ ووقت مناسبتك',
    where: 'أين',
    whereHint: 'أضف موقع مناسبتك',
    date: 'التاريخ',
    startTime: 'وقت البدء',
    endTime: 'وقت الانتهاء',
    venueName: 'اسم المكان',
    areaAddress: 'المنطقة / العنوان',
    useCurrentLocation: 'استخدم موقعي الحالي',
    pickOnMap: 'اختر الموقع على الخريطة',
    chooseLocation: 'اختر موقعًا',
    confirmLocation: 'تأكيد الموقع',
    searchLocation: 'ابحث عن مكان أو عنوان',
    locationHint: 'اكتب 3 أحرف على الأقل للبحث في OpenStreetMap',
    locationNoResults: 'لم يتم العثور على أماكن. جرّب بحثًا مختلفًا.',
    locationError: 'تعذّر البحث الآن. تحقق من اتصالك.',
    chooseTheme: 'اختر تصميمًا',
    themes: 'التصاميم',
    useThisTheme: 'استخدم هذا التصميم',
    preview: 'معاينة',
    publish: 'نشر المناسبة',
    draftSaved: 'تم حفظ المسودة',
    whenWhere: 'متى وأين',
    stepProgress: 'الخطوة {{current}} من {{total}}',
    selectDate: 'اختر التاريخ',
    selectTime: 'اختر الوقت',
    dateTBD: 'التاريخ والوقت',
    locationTBD: 'الموقع',
    visibility: 'الظهور',
    visibilityPublic: 'مناسبة عامة',
    visibilityPrivate: 'مناسبة خاصة',
    visibilityPublicHint: 'أي شخص لديه الرابط يمكنه الرؤية والانضمام',
    visibilityPrivateHint: 'فقط المدعوون يمكنهم رؤية هذه المناسبة',
    published: 'مناسبتك أصبحت جاهزة!',
    publishing: 'جارٍ النشر…',
    publishError: 'تعذّر نشر المناسبة. مسودتك محفوظة—حاول مرة أخرى.',
    discardTitle: 'تجاهل هذه المسودة؟',
    discardMessage: 'سيتم فقدان تقدمك في هذه المناسبة.',
    discard: 'تجاهل',
    keepEditing: 'متابعة التعديل',
    errorTitleRequired: 'أضف اسمًا لمناسبتك',
    errorTitleTooLong: 'الاسم طويل جدًا',
    errorDescriptionTooLong: 'الوصف طويل جدًا',
    errorCategoryRequired: 'اختر فئة',
    errorDateRequired: 'اختر التاريخ والوقت',
    errorEndBeforeStart: 'وقت الانتهاء يجب أن يكون بعد البدء',
    errorVenueRequired: 'أضف اسم المكان',
    errorAddressRequired: 'أضف المنطقة أو العنوان',
  },
  drafts: {
    title: 'مسوداتي',
    subtitle: 'أكمل تجهيز مناسباتك',
    emptyTitle: 'لا توجد مسودات بعد',
    emptyMessage: 'ابدأ إنشاء مناسبة وسيتم حفظها هنا.',
    lastEdited: 'آخر تعديل {{when}}',
    untitled: 'مناسبة بدون عنوان',
    delete: 'حذف',
    resume: 'متابعة',
  },
  themeNames: {
    wedding: 'أنيق',
    birthday: 'احتفال',
    dinner: 'عشاء',
    travel: 'سفر',
    generic: 'بسيط',
  },
  categories: {
    birthday: 'عيد ميلاد',
    wedding: 'زفاف',
    engagement: 'خطوبة',
    dinner: 'عشاء',
    trip: 'رحلة',
    gathering: 'لمة',
    iftar: 'إفطار',
    other: 'أخرى',
  },
  share: {
    title: 'مشاركة الدعوة',
    tagline: 'انشر المحبة · اجمع الناس',
    whatsapp: 'واتساب',
    copyLink: 'نسخ الرابط',
    messagePreview: 'معاينة رسالة الدعوة',
    invitedTo: 'أنت مدعو إلى {{title}}',
    footer: 'مع بعض · مصر أحلى',
  },
  discover: {
    title: 'استكشف',
    subtitle: 'اكتشف المناسبات العامة القريبة منك',
    searchPlaceholder: 'ابحث عن مناسبات أو مضيفين أو أماكن',
    trending: 'الأكثر رواجًا',
    categories: 'تصفح حسب الفئة',
    nearby: 'يحدث في مصر',
    emptyTitle: 'لا توجد مناسبات',
    emptyMessage: 'جرّب بحثًا أو فئة مختلفة.',
  },
  notifications: {
    title: 'الإشعارات',
    subtitle: 'ابقَ على تواصل مع أحبابك',
    markAllRead: 'تعليم الكل كمقروء',
    today: 'اليوم',
    earlier: 'سابقًا',
    emptyTitle: 'لا يوجد جديد',
    emptyMessage: 'ستظهر الدعوات والردود والتحديثات هنا.',
  },
  profile: {
    title: 'الملف والإعدادات',
    subtitle: 'مناسباتك. مجتمعك. لمتك.',
    hostedEvents: 'استضاف {{count}} مناسبة',
    joined: 'انضم إلى {{count}}',
    language: 'اللغة',
    notifications: 'الإشعارات',
    notificationsHint: 'تذكيرات وتحديثات المناسبات والمزيد',
    appearance: 'المظهر',
    lightMode: 'الوضع الفاتح',
    darkMode: 'الوضع الداكن',
    myDrafts: 'مسوداتي',
    myDraftsHint: 'أكمل تجهيز مناسباتك',
    savedThemes: 'التصاميم المحفوظة',
    savedThemesHint: 'أفكار مناسباتك المفضلة',
    help: 'المساعدة والدعم',
    helpHint: 'الأسئلة الشائعة والتواصل والمزيد',
    signOut: 'تسجيل الخروج',
    signOutHint: 'إلى اللقاء!',
    guest: 'ضيف',
    upgradePrompt: 'سجّل الدخول لحفظ مناسباتك',
    editProfileTitle: 'تعديل الملف الشخصي',
    displayNameLabel: 'الاسم الظاهر',
    displayNamePlaceholder: 'اسمك',
    profileSaved: 'تم تحديث الملف الشخصي',
    upgradeTitle: 'سجّل الدخول إلى لمّة',
    upgradeSubtitle: 'احتفظ بمناسباتك ومسوداتك وردودك على جميع أجهزتك.',
  },
  language: {
    title: 'اللغة',
    english: 'English',
    arabic: 'العربية',
    restartHint: 'يُعاد تشغيل التطبيق لتطبيق اللغة واتجاه الواجهة.',
  },
  settings: {
    defaultBio: 'ناس طيبين. أيام أحلى.',
    editProfile: 'تعديل الملف',
    notificationsTitle: 'الإشعارات',
    remindersLabel: 'تذكيرات المناسبات',
    remindersHint: 'احصل على تذكير قبل بدء المناسبات',
    rsvpsLabel: 'تحديثات الردود',
    rsvpsHint: 'عندما يرد ضيوفك على مناسباتك',
    updatesLabel: 'تحديثات المناسبة',
    updatesHint: 'المنشورات والتغييرات من المضيفين',
    invitesLabel: 'الدعوات الجديدة',
    invitesHint: 'عندما يدعوك أحدهم',
    appearanceTitle: 'المظهر',
    appearanceHint: 'اختر شكل لمة',
    light: 'الوضع الفاتح',
    dark: 'الوضع الداكن',
    system: 'حسب النظام',
    helpTitle: 'المساعدة والدعم',
    faq: 'الأسئلة الشائعة',
    contactUs: 'تواصل معنا',
    terms: 'شروط الخدمة',
    privacy: 'سياسة الخصوصية',
    appVersion: 'لمة الإصدار {{version}}',
    savedThemesTitle: 'التصاميم المحفوظة',
    savedThemesHint: 'اضغط على القلب لحفظ المفضلة',
    savedThemesEmpty: 'لا توجد تصاميم محفوظة بعد',
  },
};
