export const en = {
  common: {
    appName: 'Lamma',
    continue: 'Continue',
    next: 'Next',
    back: 'Back',
    cancel: 'Cancel',
    save: 'Save',
    done: 'Done',
    seeAll: 'See all',
    retry: 'Try again',
    loading: 'Loading…',
    signIn: 'Sign in',
    edit: 'Edit',
    copy: 'Copy',
    copied: 'Copied!',
    share: 'Share',
  },
  errors: {
    unexpectedTitle: 'Lamma hit a snag',
    unexpectedMessage:
      'Your plans are safe. Try again to return to your gathering.',
  },
  tabs: {
    home: 'Home',
    discover: 'Discover',
    create: 'Create',
    games: 'Games',
    notifications: 'Notifications',
    profile: 'Profile',
  },
  onboarding: {
    slide1Title: 'Create beautiful gatherings.',
    slide1Subtitle: "Invite everyone. Know who's coming.",
    slide2Title: 'Special moments with your people',
    slide2Subtitle: 'Birthdays, weddings and everything in between.',
    slide3Title: 'New places. Brighter stories.',
    slide3Subtitle: 'Plan trips and gatherings across Egypt.',
    slide4Title: 'Good food. Great people.',
    slide4Subtitle: 'Bring everyone together around the table.',
    tagline: 'PEOPLE · EVENTS · A BRIGHTER EGYPT TOGETHER',
    skip: 'Skip',
    getStarted: 'Get started',
  },
  auth: {
    welcomeTitle: 'Welcome to Lamma',
    welcomeSubtitle: 'Plan, invite and celebrate together.',
    continueAsGuest: 'Continue as guest',
    continueWithGoogle: 'Continue with Google',
    continueWithApple: 'Continue with Apple',
    or: 'or',
    noPhoneTitle: 'No phone number. No SMS codes.',
    noPhoneSubtitle: 'Guest activity stays with your account when you upgrade.',
    signingIn: 'Signing you in…',
    errorGeneric: 'We could not sign you in. Please try again.',
    errorPlayServices:
      'Google Play Services is required. Install it from the Play Store, then try again.',
  },
  home: {
    greeting: 'Good evening,',
    upcoming: 'Upcoming',
    hosting: 'Hosting',
    past: 'Past',
    yourEvents: 'Your events',
    youreGoing: "YOU'RE GOING",
    going: 'going',
    createEvent: 'Create an event',
    emptyUpcomingTitle: 'No upcoming events yet',
    emptyUpcomingMessage: 'Create your first gathering and invite your people.',
    emptyHostingTitle: "You're not hosting anything",
    emptyHostingMessage: 'Start planning and bring everyone together.',
    emptyPastTitle: 'No past events',
    emptyPastMessage: 'Your memories will show up here.',
  },
  event: {
    youAreHosting: "YOU'RE HOSTING",
    shareInvite: 'Share invite',
    manageGuests: 'Guest list',
    notFoundTitle: 'Event not found',
    notFoundMessage: 'This invite link may be wrong, or the event was removed.',
    hostedBy: 'Hosted by',
    contactHost: 'Contact host',
    openInMaps: 'Open in Maps',
    going: 'Going',
    maybe: 'Maybe',
    cantGo: "Can't go",
    peopleGoing: '{{count}} people are going',
    onePersonGoing: '1 person is going',
    eventUpdates: 'Event updates',
    pinned: 'Pinned',
    guestList: 'Guest list',
    hosts: 'Hosts',
    family: 'Family',
    friends: 'Friends',
    declined: 'Declined',
    eventCreator: 'Event creator',
    reminderDayTitle: '{{title}} is tomorrow',
    reminderDayBody: '{{when}} · {{place}}',
    reminderHourTitle: '{{title}} starts in 1 hour',
    reminderHourBody: '{{place}}',
    coHost: 'Co-host',
  },
  create: {
    title: 'Create event',
    stepBasics: 'Basics',
    stepDetails: 'Details',
    stepLocation: 'Location',
    stepInvite: 'Invite',
    eventTitle: 'Event title',
    eventTitlePlaceholder: "e.g. Mostafa's Birthday Dinner",
    category: 'Category',
    categoryHint: 'Choose the category that best fits your event',
    description: 'Description',
    descriptionPlaceholder: 'Tell your guests what to expect…',
    livePreview: 'Live invite preview',
    livePreviewHint: 'This is how your event will appear',
    when: 'When',
    whenHint: 'Set the date and time for your event',
    where: 'Where',
    whereHint: 'Add the location for your event',
    date: 'Date',
    startTime: 'Start time',
    endTime: 'End time',
    venueName: 'Venue name',
    areaAddress: 'Area / Address',
    useCurrentLocation: 'Use my current location',
    pickOnMap: 'Pick location on the map',
    chooseLocation: 'Choose a location',
    confirmLocation: 'Confirm location',
    searchLocation: 'Search for a place or address',
    locationHint: 'Type at least 3 characters to search OpenStreetMap',
    locationNoResults: 'No places found. Try a different search.',
    locationError: 'Could not search right now. Check your connection.',
    locationConfirmError:
      'Could not resolve this location. Move the pin and try again.',
    mapUnavailable:
      'The map could not load. Check that the native Google Maps API key is configured.',
    chooseTheme: 'Choose a theme',
    customTheme: 'Custom',
    themes: 'Themes',
    useThisTheme: 'Use this theme',
    preview: 'Preview',
    publish: 'Publish event',
    draftSaved: 'Draft saved',
    whenWhere: 'When & where',
    stepProgress: 'Step {{current}} of {{total}}',
    selectDate: 'Select a date',
    selectTime: 'Select a time',
    dateTBD: 'Date & time',
    locationTBD: 'Location',
    visibility: 'Visibility',
    visibilityPublic: 'Public event',
    visibilityPrivate: 'Private event',
    visibilityPublicHint: 'Anyone with the link can see and join',
    visibilityPrivateHint: 'Only invited guests can see this event',
    published: 'Your event is live!',
    publishing: 'Publishing…',
    publishError:
      'Could not publish your event. Your draft is safe—please try again.',
    storageUnauthorized:
      'Could not upload your cover photo. Your draft is saved—please try again.',
    discardTitle: 'Discard this draft?',
    discardMessage: 'Your progress on this event will be lost.',
    discard: 'Discard',
    keepEditing: 'Keep editing',
    errorTitleRequired: 'Add a title for your event',
    errorTitleTooLong: 'Title is too long',
    errorDescriptionTooLong: 'Description is too long',
    errorCategoryRequired: 'Pick a category',
    errorDateRequired: 'Choose a date and time',
    errorEndBeforeStart: 'End time must be after the start',
    errorVenueRequired: 'Add a venue name',
    errorAddressRequired: 'Add an area or address',
  },
  drafts: {
    title: 'My drafts',
    subtitle: 'Continue building your events',
    emptyTitle: 'No drafts yet',
    emptyMessage: 'Start creating an event and it will be saved here.',
    lastEdited: 'Edited {{when}}',
    untitled: 'Untitled event',
    delete: 'Delete',
    resume: 'Continue',
  },
  themeNames: {
    wedding: 'Elegant',
    birthday: 'Party',
    dinner: 'Dinner',
    travel: 'Travel',
    generic: 'Minimal',
  },
  categories: {
    birthday: 'Birthday',
    wedding: 'Wedding',
    engagement: 'Engagement',
    dinner: 'Dinner',
    trip: 'Trip',
    gathering: 'Gathering',
    iftar: 'Iftar',
    other: 'Other',
  },
  share: {
    title: 'Share invite',
    tagline: 'SPREAD LOVE · BRING PEOPLE TOGETHER',
    whatsapp: 'WhatsApp',
    copyLink: 'Copy link',
    messagePreview: 'INVITE MESSAGE PREVIEW',
    invitedTo: "You're invited to {{title}}",
    shareError: 'Could not open the share sheet. Please try again.',
    footer: 'TOGETHER · A BRIGHTER EGYPT',
  },
  discover: {
    all: 'All',
    title: 'Discover',
    subtitle: 'Find public events near you',
    searchPlaceholder: 'Search events, hosts, places',
    trending: 'Trending now',
    categories: 'Browse by category',
    nearby: 'Happening around Egypt',
    emptyTitle: 'No events found',
    emptyMessage: 'Try a different search or category.',
  },
  games: {
    title: 'Games',
    subtitle:
      'Pick a game, host a lobby, and play together on everyone’s device.',
    playersRange: '{{min}}–{{max}} players',
    hostAuthoritative: 'Host-led sync',
    joinRoom: 'Join a room',
    playerName: 'Player name',
    joinGame: 'Join game',
    joinCodeRequired: 'Enter a room code.',
    joinCodeNotFound: 'No room found for that code.',
    availableRooms: 'Available rooms',
    roomSummary: '{{code}} · {{count}} connected',
    roomCode: 'Room code',
    sharedSessionHint:
      'Share the link or code with your friends. They can join from anywhere, no need to be on the same Wi‑Fi.',
    copyCode: 'Copy code',
    codeCopied: 'Copied!',
    shareInvite: 'Share invite',
    shareRoomMessage:
      'Join my {{game}} game on Lamma! Tap to open: {{link}}\nOr enter room code {{code}} in Games.',
    joiningRoom: 'Joining room {{code}}…',
    inviteExpired:
      'Room {{code}} has ended or does not exist. Ask the host for a new link.',
    players: 'Players',
    host: 'Host',
    disconnected: 'Disconnected',
    startGame: 'Start game',
    inGame: 'Game started',
    leaveLobby: 'Leave lobby',
    triviaSetup: 'Trivia setup',
    triviaPack: 'Pack: {{pack}}',
    triviaQuestions: '{{count}} questions · {{seconds}}s each',
    triviaPrizeHint: 'Prize text appears before the round and to the winner.',
    choosePack: 'Choose pack',
    questionCount: 'Questions',
    timePerQuestion: 'Time per question',
    secondsShort: '{{seconds}}s',
    prize: 'Prize',
    prizePlaceholder: 'Winner picks the next playlist',
    yourSecretRole: 'Your secret role',
    noRoleYet: 'No role yet',
    revealVote: 'Reveal vote',
    nextPhase: 'Next phase',
    triviaQuestionProgress: 'Question {{current}}/{{total}}',
    triviaTimer: '{{seconds}}s',
    revealAnswer: 'Reveal answer',
    nextQuestion: 'Next question',
    leaderboard: 'Leaderboard',
    triviaWinner: '{{name}} wins',
    triviaPrizeAward: 'Prize: {{prize}}',
    roundNumber: 'Round {{round}}',
    noPlayer: 'No player',
    noPrompt: 'No prompt ready',
    icebreakerPromptPrivate: 'Prompt is on their device.',
    nextPrompt: 'Next prompt',
    icebreakersSetup: 'Icebreakers setup',
    icebreakersPromptCount: '{{count}} prompts bundled',
    icebreakersRotation: 'Turns rotate evenly before repeating players.',
    quarterMileSetup: 'Quarter Mile setup',
    quarterMileChooseCategory: 'Choose a category',
    quarterMilePackLine: '{{pack}} · {{count}} picks',
    quarterMileHint: 'Each turn you see one pick and one hidden pick. Keep the one you see or gamble on the hidden one. Strongest team wins.',
    quarterMileKnown: 'On the table',
    quarterMileHidden: 'Hidden pick',
    quarterMileTake: 'Take it',
    quarterMileLeave: 'Leave it (take hidden)',
    quarterMileYourGarage: 'Your team',
    quarterMileScores: 'Team scores',
    quarterMileWinner: '{{name}} wins!',
    quarterMileWaiting: 'Waiting for {{name}} to choose…',
    quarterMileRevealPair: '{{name}} chose {{choice}}',
    quarterMileChoiceTake: 'the one on the table',
    quarterMileChoiceLeave: 'the hidden pick',
    needPlayers: 'Need at least {{count}} players to start ({{have}} here now).',
    waitingForHostStart: 'Waiting for the host to start the game…',
    waitingForHost: 'Waiting for the host…',
    lateJoinerTitle: 'Game already in progress',
    lateJoinerMessage: 'You joined after this round started. You\'ll be dealt in when the host starts the next round.',
    spectatorQuarterMile: 'Quarter Mile is a 2-player duel. You are watching this one.',
    playAgain: 'Play again',
    actionFailed: 'That didn\'t go through. Check your connection and try again.',
    actionFailedTitle: 'Could not send',
    triviaTimeLeft: '{{seconds}}s left',
    triviaAnswered: '{{count}}/{{total}} answered',
    triviaYouAnswered: 'Answer locked in. Waiting for the others…',
    icebreakerYourTurn: 'It\'s your turn! Answer out loud, then tap Done.',
    icebreakerDone: 'Done, next person',
    icebreakerWaiting: '{{name}} is answering…',
    imposterSetup: 'How Imposter works',
    imposterRule1: 'Everyone gets the same secret word, except one random imposter who only sees the category.',
    imposterRule2: 'Take turns saying one short clue about the word. Not too obvious!',
    imposterRule3: 'Everyone votes on their phone for who they think the imposter is.',
    imposterRule4: 'Catch the imposter and they get one last guess at the word. A tie or a wrong vote means the imposter wins.',
    imposterRound: 'Round {{round}}',
    imposterCategory: 'Category: {{category}}',
    imposterYourWord: 'Your secret word',
    imposterYouAre: 'You are the IMPOSTER',
    imposterYouAreHint: 'Blend in. Listen to the clues and guess the word so no one notices.',
    imposterNotIn: 'Watching this round',
    imposterCluesTitle: 'Clue time — speaking order',
    imposterCluesHint: 'Each player says one short clue out loud, in this order. Then the host opens the vote.',
    imposterStartVote: 'Open the vote',
    imposterVoteTitle: 'Who is the imposter?',
    imposterVoted: 'Vote sent. Waiting for everyone… ({{count}}/{{total}})',
    imposterRevealVotes: 'Reveal votes now',
    imposterGuessTitle: '{{name}} was caught! Last chance to guess the word.',
    imposterGuessYou: 'You were caught! Guess the secret word to steal the win:',
    imposterGuessWaiting: '{{name}} is guessing the word…',
    imposterSkipGuess: 'Skip guess',
    imposterPlayersWin: 'Players win! The imposter was {{name}}.',
    imposterWins: 'The imposter wins! It was {{name}}.',
    imposterTie: 'The vote was a tie, so no one was voted out.',
    imposterWrongOut: '{{name}} was voted out, but they were innocent.',
    imposterGuessedRight: '{{name}} guessed the word correctly.',
    imposterGuessedWrong: '{{name}} guessed wrong.',
    imposterWordWas: 'The word was: {{word}}',
    imposterVotesFor: '{{name}}: {{count}} votes',
    imposterVotesFor_one: '{{name}}: {{count}} vote',
    imposterVotesFor_other: '{{name}}: {{count}} votes',
    imposterScores: 'Scores',
    imposterNextRound: 'Next round',
    quarterMileNextPair: 'Next pair',
    loadingContentTitle: 'Loading games',
    loadingContentMessage:
      'Getting the latest game rules, questions, and prompts.',
    contentErrorTitle: 'Games could not load',
    contentErrorMessage:
      'Check the connection and try again. Previously loaded games stay cached on this device.',
    contentEmptyTitle: 'No games available',
    contentEmptyMessage:
      'Seed the games collection before hosting a room from this device.',
    retry: 'Try again',
  },
  notifications: {
    title: 'Notifications',
    subtitle: 'Stay in the loop with your people',
    markAllRead: 'Mark all read',
    today: 'Today',
    earlier: 'Earlier',
    emptyTitle: "You're all caught up",
    emptyMessage: 'Invites, RSVPs and updates will appear here.',
  },
  profile: {
    title: 'Profile & Settings',
    subtitle: 'Your events. Your community. Your Lamma.',
    hostedEvents: 'Hosted {{count}} events',
    oneHostedEvent: 'Hosted 1 event',
    joined: 'Joined {{count}}',
    language: 'Language',
    notifications: 'Notifications',
    notificationsHint: 'Event reminders, updates and more',
    appearance: 'Appearance',
    lightMode: 'Light mode',
    darkMode: 'Dark mode',
    myDrafts: 'My drafts',
    myDraftsHint: 'Continue building your events',
    help: 'Help & support',
    helpHint: 'FAQs, contact us, and more',
    signOut: 'Sign out',
    signOutHint: 'See you soon!',
    guest: 'Guest',
    upgradePrompt: 'Sign in to save your events',
    editProfileTitle: 'Edit profile',
    displayNameLabel: 'Display name',
    displayNamePlaceholder: 'Your name',
    profileSaved: 'Profile updated',
    upgradeTitle: 'Sign in to Lamma',
    upgradeSubtitle: 'Keep your events, drafts and RSVPs across your devices.',
  },
  language: {
    title: 'Language',
    english: 'English',
    arabic: 'العربية',
    restartHint:
      'The app restarts to apply your language and layout direction.',
  },
  settings: {
    defaultBio: 'Good people. Brighter days.',
    editProfile: 'Edit profile',
    notificationsTitle: 'Notifications',
    remindersLabel: 'Event reminders',
    remindersHint: 'Get reminded before events start',
    rsvpsLabel: 'RSVP updates',
    rsvpsHint: 'When guests respond to your events',
    updatesLabel: 'Event updates',
    updatesHint: 'Posts and changes from hosts',
    invitesLabel: 'New invitations',
    invitesHint: 'When someone invites you',
    appearanceTitle: 'Appearance',
    appearanceHint: 'Choose how Lamma looks',
    light: 'Light mode',
    dark: 'Dark mode',
    system: 'Match system',
    helpTitle: 'Help & support',
    faq: 'Frequently asked questions',
    contactUs: 'Contact us',
    terms: 'Terms of service',
    privacy: 'Privacy policy',
    appVersion: 'Lamma v{{version}}',
  },
  guests: {
    summaryGoing: '{{count}} going',
    summaryMaybe: '{{count}} maybe',
    summaryDeclined: '{{count}} declined',
    emptyGoingTitle: 'No one is going yet',
    emptyGoingMessage: 'Share the invite so your guests can RSVP.',
    emptyMaybeTitle: 'No maybes yet',
    emptyMaybeMessage: 'Guests who answer Maybe will show up here.',
    emptyDeclinedTitle: 'No one declined',
    emptyDeclinedMessage: "Guests who can't make it will show up here.",
  },
  profileSetup: {
    title: 'Set up your profile',
    subtitle:
      "Add your name and a photo so friends know it's you. You can skip this and do it later.",
    addPhoto: 'Add photo',
    changePhoto: 'Change photo',
    removePhoto: 'Remove',
    save: 'Save and continue',
    skip: 'Skip for now',
    photoError: 'Could not open your photos. Please try again.',
    saveError:
      'Could not save your profile. Check your connection and try again.',
  },
  info: {
    sectionTitle: 'About Lamma',
    aboutTitle: 'About Lamma',
    aboutHint: 'What Lamma is and who makes it',
    contactTitle: 'Contact us',
    contactHint: 'Questions, feedback or support',
    termsTitle: 'Terms of Service',
    termsHint: 'The rules for using Lamma',
    privacyTitle: 'Privacy Policy',
    privacyHint: 'What we collect and why',
    lastUpdated: 'Last updated: September 2026',
    openWebsite: 'Open lamma-links.vercel.app',
    version: 'Version {{version}}',
    about: {
      tagline: 'Gather your people.',
      intro:
        'Lamma (لمّة, "a gathering") helps you plan events and bring friends and family together, from birthdays and weddings to dinners, trips and Iftar.',
      s1Title: 'Plan events',
      s1Body:
        'Create an event in a few steps, pick a theme or your own cover photo, and share a beautiful invite link on WhatsApp or anywhere else.',
      s2Title: 'Know who is coming',
      s2Body:
        "Guests answer Going, Maybe or Can't go, and hosts see the whole guest list in one place.",
      s3Title: 'Play together',
      s3Body:
        'Start a party game such as Trivia, Imposter, Icebreakers or Quarter Mile, and everyone plays on their own phone.',
      s4Title: 'Made in Egypt',
      s4Body:
        'Lamma is built in Egypt, in Arabic and English, for the way we celebrate.',
    },
    contact: {
      intro:
        'We would love to hear from you. Send us your questions, ideas or problems and we will reply as soon as we can.',
      emailLabel: 'Email',
      sendEmail: 'Send us an email',
      responseTime: 'We usually reply within 2 to 3 business days.',
      reportTitle: 'Reporting a problem',
      reportBody:
        'Tell us what happened, which screen you were on and your phone model. Screenshots help a lot.',
      emailSubject: 'Lamma support',
      emailError: 'No email app found. Write to us at {{email}}.',
    },
    terms: {
      intro:
        'By using Lamma you agree to these terms. Please read them carefully.',
      s1Title: '1. Using Lamma',
      s1Body:
        'You can use Lamma as a guest or with a Google or Apple account. You are responsible for the activity on your account and for keeping your device secure.',
      s2Title: '2. Your content',
      s2Body:
        'You own the events, photos, names and messages you add. You allow Lamma to store them and show them to the people you share them with, only to run the service.',
      s3Title: '3. Acceptable use',
      s3Body:
        'Do not use Lamma for anything illegal, hateful, harassing or misleading, and do not upload content you do not have the right to share. We may remove content or suspend accounts that break these rules.',
      s4Title: '4. Events and invites',
      s4Body:
        'Hosts are responsible for their events. Anyone with an invite link can view that event, so only share links with people you trust. Lamma does not organise and is not responsible for events created in the app.',
      s5Title: '5. Games',
      s5Body:
        'Party games are for fun. Any prize mentioned in a game is arranged by the host, not by Lamma.',
      s6Title: '6. Availability',
      s6Body:
        'Lamma is provided "as is". We work to keep it running, but we cannot promise it will always be available or error-free. Events are deleted automatically after they end.',
      s7Title: '7. Changes',
      s7Body:
        'We may update these terms. If a change is important we will tell you in the app. Using Lamma after a change means you accept the updated terms.',
      s8Title: '8. Contact',
      s8Body: 'Questions about these terms? Email {{email}}.',
    },
    privacy: {
      intro:
        'Your privacy matters to us. This policy explains what Lamma collects, why, and the choices you have.',
      s1Title: 'What we collect',
      s1Body:
        'Account data (an anonymous ID for guests, or your name, email and photo from Google or Apple), the profile name and photo you choose, the events you create and your RSVPs, game activity, and basic device data such as the notification token, app version and crash reports.',
      s2Title: 'How we use it',
      s2Body:
        'Only to run the app: show your events and invites, sync RSVPs and games, send the reminders and notifications you enabled, fix crashes and improve Lamma. We do not sell your data and we do not show ads.',
      s3Title: 'Who can see it',
      s3Body:
        'Event details are visible to people who have the invite link. Your name and RSVP are visible to the event host and guests. Your profile photo stays in your account.',
      s4Title: 'Service providers',
      s4Body:
        'Lamma uses Google Firebase (sign-in, database, notifications, analytics and crash reports) to store and process data for us.',
      s5Title: 'Security',
      s5Body:
        'Data is sent over encrypted connections. On your phone, the guest session token is kept in encrypted storage protected by the device keychain.',
      s6Title: 'Your choices',
      s6Body:
        'You can change your name, turn notifications off in Settings, delete your events or sign out at any time. To delete your account and data, email us and we will do it.',
      s7Title: 'Children',
      s7Body: 'Lamma is not meant for children under 13.',
      s8Title: 'Contact',
      s8Body: 'Questions about privacy? Email {{email}}.',
    },
  },
};

export type TranslationSchema = typeof en;
