export const en = {
  common: {
    appName: 'Lamma',
    continue: 'Continue',
    next: 'Next',
    back: 'Back',
    cancel: 'Cancel',
    save: 'Save',
    done: 'Done',
    seeAll: 'See all',
    retry: 'Try again',
    loading: 'Loading…',
    signIn: 'Sign in',
    edit: 'Edit',
    copy: 'Copy',
    copied: 'Copied!',
    share: 'Share',
  },
  tabs: {
    home: 'Home',
    discover: 'Discover',
    create: 'Create',
    notifications: 'Notifications',
    profile: 'Profile',
  },
  onboarding: {
    slide1Title: 'Create beautiful gatherings.',
    slide1Subtitle: "Invite everyone. Know who's coming.",
    slide2Title: 'Special moments with your people',
    slide2Subtitle: 'Birthdays, weddings and everything in between.',
    slide3Title: 'New places. Brighter stories.',
    slide3Subtitle: 'Plan trips and gatherings across Egypt.',
    slide4Title: 'Good food. Great people.',
    slide4Subtitle: 'Bring everyone together around the table.',
    tagline: 'PEOPLE · EVENTS · A BRIGHTER EGYPT TOGETHER',
    skip: 'Skip',
    getStarted: 'Get started',
  },
  auth: {
    welcomeTitle: 'Welcome to Lamma',
    welcomeSubtitle: 'Plan, invite and celebrate together.',
    continueAsGuest: 'Continue as guest',
    continueWithGoogle: 'Continue with Google',
    continueWithApple: 'Continue with Apple',
    or: 'or',
    noPhoneTitle: 'No phone number. No SMS codes.',
    noPhoneSubtitle: 'Guest activity stays with your account when you upgrade.',
    signingIn: 'Signing you in…',
    errorGeneric: 'We could not sign you in. Please try again.',
  },
  home: {
    greeting: 'Good evening,',
    upcoming: 'Upcoming',
    hosting: 'Hosting',
    past: 'Past',
    yourEvents: 'Your events',
    youreGoing: "YOU'RE GOING",
    going: 'going',
    createEvent: 'Create an event',
    emptyUpcomingTitle: 'No upcoming events yet',
    emptyUpcomingMessage: 'Create your first gathering and invite your people.',
    emptyHostingTitle: "You're not hosting anything",
    emptyHostingMessage: 'Start planning and bring everyone together.',
    emptyPastTitle: 'No past events',
    emptyPastMessage: 'Your memories will show up here.',
  },
  event: {
    hostedBy: 'Hosted by',
    contactHost: 'Contact host',
    openInMaps: 'Open in Maps',
    going: 'Going',
    maybe: 'Maybe',
    cantGo: "Can't go",
    peopleGoing: '{{count}} people are going',
    eventUpdates: 'Event updates',
    pinned: 'Pinned',
    guestList: 'Guest list',
    hosts: 'Hosts',
    family: 'Family',
    friends: 'Friends',
    declined: 'Declined',
    eventCreator: 'Event creator',
    coHost: 'Co-host',
  },
  create: {
    title: 'Create event',
    stepBasics: 'Basics',
    stepDetails: 'Details',
    stepLocation: 'Location',
    stepInvite: 'Invite',
    eventTitle: 'Event title',
    eventTitlePlaceholder: "e.g. Mostafa's Birthday Dinner",
    category: 'Category',
    categoryHint: 'Choose the category that best fits your event',
    description: 'Description',
    descriptionPlaceholder: 'Tell your guests what to expect…',
    livePreview: 'Live invite preview',
    livePreviewHint: 'This is how your event will appear',
    when: 'When',
    whenHint: 'Set the date and time for your event',
    where: 'Where',
    whereHint: 'Add the location for your event',
    date: 'Date',
    startTime: 'Start time',
    endTime: 'End time',
    timezone: 'Timezone',
    venueName: 'Venue name',
    areaAddress: 'Area / Address',
    useCurrentLocation: 'Use my current location',
    pickOnMap: 'Pick location on the map',
    chooseLocation: 'Choose a location',
    confirmLocation: 'Confirm location',
    searchLocation: 'Search for a place or address',
    locationHint: 'Type at least 3 characters to search OpenStreetMap',
    locationNoResults: 'No places found. Try a different search.',
    locationError: 'Could not search right now. Check your connection.',
    chooseTheme: 'Choose a theme',
    themes: 'Themes',
    useThisTheme: 'Use this theme',
    preview: 'Preview',
    publish: 'Publish event',
    draftSaved: 'Draft saved',
    whenWhere: 'When & where',
    stepProgress: 'Step {{current}} of {{total}}',
    selectDate: 'Select a date',
    selectTime: 'Select a time',
    selectTimezone: 'Select a timezone',
    dateTBD: 'Date & time',
    locationTBD: 'Location',
    visibility: 'Visibility',
    visibilityPublic: 'Public event',
    visibilityPrivate: 'Private event',
    visibilityPublicHint: 'Anyone with the link can see and join',
    visibilityPrivateHint: 'Only invited guests can see this event',
    published: 'Your event is live!',
    publishing: 'Publishing…',
    discardTitle: 'Discard this draft?',
    discardMessage: 'Your progress on this event will be lost.',
    discard: 'Discard',
    keepEditing: 'Keep editing',
    errorTitleRequired: 'Add a title for your event',
    errorTitleTooLong: 'Title is too long',
    errorDescriptionTooLong: 'Description is too long',
    errorCategoryRequired: 'Pick a category',
    errorDateRequired: 'Choose a date and time',
    errorEndBeforeStart: 'End time must be after the start',
    errorVenueRequired: 'Add a venue name',
    errorAddressRequired: 'Add an area or address',
  },
  drafts: {
    title: 'My drafts',
    subtitle: 'Continue building your events',
    emptyTitle: 'No drafts yet',
    emptyMessage: 'Start creating an event and it will be saved here.',
    lastEdited: 'Edited {{when}}',
    untitled: 'Untitled event',
    delete: 'Delete',
    resume: 'Continue',
  },
  themeNames: {
    wedding: 'Elegant',
    birthday: 'Party',
    dinner: 'Dinner',
    travel: 'Travel',
    generic: 'Minimal',
  },
  categories: {
    birthday: 'Birthday',
    wedding: 'Wedding',
    engagement: 'Engagement',
    dinner: 'Dinner',
    trip: 'Trip',
    gathering: 'Gathering',
    iftar: 'Iftar',
    other: 'Other',
  },
  share: {
    title: 'Share invite',
    tagline: 'SPREAD LOVE · BRING PEOPLE TOGETHER',
    whatsapp: 'WhatsApp',
    copyLink: 'Copy link',
    messagePreview: 'INVITE MESSAGE PREVIEW',
    invitedTo: "You're invited to {{title}}",
    footer: 'TOGETHER · A BRIGHTER EGYPT',
  },
  discover: {
    title: 'Discover',
    subtitle: 'Find public events near you',
    searchPlaceholder: 'Search events, hosts, places',
    trending: 'Trending now',
    categories: 'Browse by category',
    nearby: 'Happening around Egypt',
    emptyTitle: 'No events found',
    emptyMessage: 'Try a different search or category.',
  },
  notifications: {
    title: 'Notifications',
    subtitle: 'Stay in the loop with your people',
    markAllRead: 'Mark all read',
    today: 'Today',
    earlier: 'Earlier',
    emptyTitle: "You're all caught up",
    emptyMessage: 'Invites, RSVPs and updates will appear here.',
  },
  profile: {
    title: 'Profile & Settings',
    subtitle: 'Your events. Your community. Your Lamma.',
    hostedEvents: 'Hosted {{count}} events',
    joined: 'Joined {{count}}',
    language: 'Language',
    notifications: 'Notifications',
    notificationsHint: 'Event reminders, updates and more',
    appearance: 'Appearance',
    lightMode: 'Light mode',
    darkMode: 'Dark mode',
    myDrafts: 'My drafts',
    myDraftsHint: 'Continue building your events',
    savedThemes: 'Saved themes',
    savedThemesHint: 'Your favorite event ideas',
    help: 'Help & support',
    helpHint: 'FAQs, contact us, and more',
    signOut: 'Sign out',
    signOutHint: 'See you soon!',
    guest: 'Guest',
    upgradePrompt: 'Sign in to save your events',
    editProfileTitle: 'Edit profile',
    displayNameLabel: 'Display name',
    displayNamePlaceholder: 'Your name',
    profileSaved: 'Profile updated',
    upgradeTitle: 'Sign in to Lamma',
    upgradeSubtitle: 'Keep your events, drafts and RSVPs across your devices.',
  },
  language: {
    title: 'Language',
    english: 'English',
    arabic: 'العربية',
    restartHint: 'The app layout updates to match your language.',
  },
  settings: {
    defaultBio: 'Good people. Brighter days.',
    editProfile: 'Edit profile',
    notificationsTitle: 'Notifications',
    remindersLabel: 'Event reminders',
    remindersHint: 'Get reminded before events start',
    rsvpsLabel: 'RSVP updates',
    rsvpsHint: 'When guests respond to your events',
    updatesLabel: 'Event updates',
    updatesHint: 'Posts and changes from hosts',
    invitesLabel: 'New invitations',
    invitesHint: 'When someone invites you',
    appearanceTitle: 'Appearance',
    appearanceHint: 'Choose how Lamma looks',
    light: 'Light mode',
    dark: 'Dark mode',
    system: 'Match system',
    helpTitle: 'Help & support',
    faq: 'Frequently asked questions',
    contactUs: 'Contact us',
    terms: 'Terms of service',
    privacy: 'Privacy policy',
    appVersion: 'Lamma v{{version}}',
    savedThemesTitle: 'Saved themes',
    savedThemesHint: 'Tap the heart to save your favorites',
    savedThemesEmpty: 'No saved themes yet',
  },
};

export type TranslationSchema = typeof en;
