export const en = {
  common: {
    appName: 'Lamma',
    continue: 'Continue',
    next: 'Next',
    back: 'Back',
    cancel: 'Cancel',
    save: 'Save',
    done: 'Done',
    seeAll: 'See all',
    retry: 'Try again',
    loading: 'Loading…',
    signIn: 'Sign in',
    edit: 'Edit',
    copy: 'Copy',
    copied: 'Copied!',
    share: 'Share',
  },
  errors: {
    unexpectedTitle: 'Lamma hit a snag',
    unexpectedMessage:
      'Your plans are safe. Try again to return to your gathering.',
  },
  tabs: {
    home: 'Home',
    discover: 'Discover',
    create: 'Create',
    games: 'Games',
    notifications: 'Notifications',
    profile: 'Profile',
  },
  onboarding: {
    slide1Title: 'Create beautiful gatherings.',
    slide1Subtitle: "Invite everyone. Know who's coming.",
    slide2Title: 'Special moments with your people',
    slide2Subtitle: 'Birthdays, weddings and everything in between.',
    slide3Title: 'New places. Brighter stories.',
    slide3Subtitle: 'Plan trips and gatherings across Egypt.',
    slide4Title: 'Good food. Great people.',
    slide4Subtitle: 'Bring everyone together around the table.',
    tagline: 'PEOPLE · EVENTS · A BRIGHTER EGYPT TOGETHER',
    skip: 'Skip',
    getStarted: 'Get started',
  },
  auth: {
    welcomeTitle: 'Welcome to Lamma',
    welcomeSubtitle: 'Plan, invite and celebrate together.',
    continueAsGuest: 'Continue as guest',
    continueWithGoogle: 'Continue with Google',
    continueWithApple: 'Continue with Apple',
    or: 'or',
    noPhoneTitle: 'No phone number. No SMS codes.',
    noPhoneSubtitle: 'Guest activity stays with your account when you upgrade.',
    signingIn: 'Signing you in…',
    errorGeneric: 'We could not sign you in. Please try again.',
    errorPlayServices:
      'Google Play Services is required. Install it from the Play Store, then try again.',
  },
  home: {
    greeting: 'Good evening,',
    upcoming: 'Upcoming',
    hosting: 'Hosting',
    past: 'Past',
    yourEvents: 'Your events',
    youreGoing: "YOU'RE GOING",
    going: 'going',
    createEvent: 'Create an event',
    emptyUpcomingTitle: 'No upcoming events yet',
    emptyUpcomingMessage: 'Create your first gathering and invite your people.',
    emptyHostingTitle: "You're not hosting anything",
    emptyHostingMessage: 'Start planning and bring everyone together.',
    emptyPastTitle: 'No past events',
    emptyPastMessage: 'Your memories will show up here.',
  },
  event: {
    notFoundTitle: 'Event not found',
    notFoundMessage: 'This invite link may be wrong, or the event was removed.',
    hostedBy: 'Hosted by',
    contactHost: 'Contact host',
    openInMaps: 'Open in Maps',
    going: 'Going',
    maybe: 'Maybe',
    cantGo: "Can't go",
    peopleGoing: '{{count}} people are going',
    onePersonGoing: '1 person is going',
    eventUpdates: 'Event updates',
    pinned: 'Pinned',
    guestList: 'Guest list',
    hosts: 'Hosts',
    family: 'Family',
    friends: 'Friends',
    declined: 'Declined',
    eventCreator: 'Event creator',
    reminderDayTitle: '{{title}} is tomorrow',
    reminderDayBody: '{{when}} · {{place}}',
    reminderHourTitle: '{{title}} starts in 1 hour',
    reminderHourBody: '{{place}}',
    coHost: 'Co-host',
  },
  create: {
    title: 'Create event',
    stepBasics: 'Basics',
    stepDetails: 'Details',
    stepLocation: 'Location',
    stepInvite: 'Invite',
    eventTitle: 'Event title',
    eventTitlePlaceholder: "e.g. Mostafa's Birthday Dinner",
    category: 'Category',
    categoryHint: 'Choose the category that best fits your event',
    description: 'Description',
    descriptionPlaceholder: 'Tell your guests what to expect…',
    livePreview: 'Live invite preview',
    livePreviewHint: 'This is how your event will appear',
    when: 'When',
    whenHint: 'Set the date and time for your event',
    where: 'Where',
    whereHint: 'Add the location for your event',
    date: 'Date',
    startTime: 'Start time',
    endTime: 'End time',
    venueName: 'Venue name',
    areaAddress: 'Area / Address',
    useCurrentLocation: 'Use my current location',
    pickOnMap: 'Pick location on the map',
    chooseLocation: 'Choose a location',
    confirmLocation: 'Confirm location',
    searchLocation: 'Search for a place or address',
    locationHint: 'Type at least 3 characters to search OpenStreetMap',
    locationNoResults: 'No places found. Try a different search.',
    locationError: 'Could not search right now. Check your connection.',
    locationConfirmError:
      'Could not resolve this location. Move the pin and try again.',
    mapUnavailable:
      'The map could not load. Check that the native Google Maps API key is configured.',
    chooseTheme: 'Choose a theme',
    customTheme: 'Custom',
    themes: 'Themes',
    useThisTheme: 'Use this theme',
    preview: 'Preview',
    publish: 'Publish event',
    draftSaved: 'Draft saved',
    whenWhere: 'When & where',
    stepProgress: 'Step {{current}} of {{total}}',
    selectDate: 'Select a date',
    selectTime: 'Select a time',
    dateTBD: 'Date & time',
    locationTBD: 'Location',
    visibility: 'Visibility',
    visibilityPublic: 'Public event',
    visibilityPrivate: 'Private event',
    visibilityPublicHint: 'Anyone with the link can see and join',
    visibilityPrivateHint: 'Only invited guests can see this event',
    published: 'Your event is live!',
    publishing: 'Publishing…',
    publishError:
      'Could not publish your event. Your draft is safe—please try again.',
    storageUnauthorized:
      'Could not upload your cover photo. Your draft is saved—please try again.',
    discardTitle: 'Discard this draft?',
    discardMessage: 'Your progress on this event will be lost.',
    discard: 'Discard',
    keepEditing: 'Keep editing',
    errorTitleRequired: 'Add a title for your event',
    errorTitleTooLong: 'Title is too long',
    errorDescriptionTooLong: 'Description is too long',
    errorCategoryRequired: 'Pick a category',
    errorDateRequired: 'Choose a date and time',
    errorEndBeforeStart: 'End time must be after the start',
    errorVenueRequired: 'Add a venue name',
    errorAddressRequired: 'Add an area or address',
  },
  drafts: {
    title: 'My drafts',
    subtitle: 'Continue building your events',
    emptyTitle: 'No drafts yet',
    emptyMessage: 'Start creating an event and it will be saved here.',
    lastEdited: 'Edited {{when}}',
    untitled: 'Untitled event',
    delete: 'Delete',
    resume: 'Continue',
  },
  themeNames: {
    wedding: 'Elegant',
    birthday: 'Party',
    dinner: 'Dinner',
    travel: 'Travel',
    generic: 'Minimal',
  },
  categories: {
    birthday: 'Birthday',
    wedding: 'Wedding',
    engagement: 'Engagement',
    dinner: 'Dinner',
    trip: 'Trip',
    gathering: 'Gathering',
    iftar: 'Iftar',
    other: 'Other',
  },
  share: {
    title: 'Share invite',
    tagline: 'SPREAD LOVE · BRING PEOPLE TOGETHER',
    whatsapp: 'WhatsApp',
    copyLink: 'Copy link',
    messagePreview: 'INVITE MESSAGE PREVIEW',
    invitedTo: "You're invited to {{title}}",
    shareError: 'Could not open the share sheet. Please try again.',
    footer: 'TOGETHER · A BRIGHTER EGYPT',
  },
  discover: {
    title: 'Discover',
    subtitle: 'Find public events near you',
    searchPlaceholder: 'Search events, hosts, places',
    trending: 'Trending now',
    categories: 'Browse by category',
    nearby: 'Happening around Egypt',
    emptyTitle: 'No events found',
    emptyMessage: 'Try a different search or category.',
  },
  games: {
    title: 'Games',
    subtitle:
      'Pick a game, host a lobby, and play together on everyone’s device.',
    playersRange: '{{min}}–{{max}} players',
    hostAuthoritative: 'Host-led sync',
    joinRoom: 'Join a room',
    playerName: 'Player name',
    joinGame: 'Join game',
    joinCodeRequired: 'Enter a room code.',
    joinCodeNotFound: 'No room found for that code.',
    availableRooms: 'Available rooms',
    roomSummary: '{{code}} · {{count}} connected',
    roomCode: 'Room code',
    sharedSessionHint:
      'Share the link or code with your friends. They can join from anywhere, no need to be on the same Wi‑Fi.',
    copyCode: 'Copy code',
    codeCopied: 'Copied!',
    shareInvite: 'Share invite',
    shareRoomMessage:
      'Join my {{game}} game on Lamma! Tap to open: {{link}}\nOr enter room code {{code}} in Games.',
    joiningRoom: 'Joining room {{code}}…',
    inviteExpired:
      'Room {{code}} has ended or does not exist. Ask the host for a new link.',
    players: 'Players',
    host: 'Host',
    disconnected: 'Disconnected',
    startGame: 'Start game',
    inGame: 'Game started',
    leaveLobby: 'Leave lobby',
    mafiosoSetup: 'Mafioso setup (clues + vote)',
    mafiosoRoleCount: '{{count}} secret roles ready',
    triviaSetup: 'Trivia setup',
    triviaPack: 'Pack: {{pack}}',
    triviaQuestions: '{{count}} questions · {{seconds}}s each',
    triviaPrizeHint: 'Prize text appears before the round and to the winner.',
    choosePack: 'Choose pack',
    questionCount: 'Questions',
    timePerQuestion: 'Time per question',
    secondsShort: '{{seconds}}s',
    prize: 'Prize',
    prizePlaceholder: 'Winner picks the next playlist',
    mafiosoPhase: 'Phase: {{phase}}',
    yourSecretRole: 'Your secret role',
    noRoleYet: 'No role yet',
    mafiosoVotePrompt: 'Vote for who should be revealed',
    mafiosoReveal: 'Reveal',
    mafiosoRevealedPlayer: '{{name}} was revealed as {{role}}',
    mafiosoNoVotes: 'No one received votes.',
    revealVote: 'Reveal vote',
    nextPhase: 'Next phase',
    triviaQuestionProgress: 'Question {{current}}/{{total}}',
    triviaTimer: '{{seconds}}s',
    revealAnswer: 'Reveal answer',
    nextQuestion: 'Next question',
    leaderboard: 'Leaderboard',
    triviaWinner: '{{name}} wins',
    triviaPrizeAward: 'Prize: {{prize}}',
    roundNumber: 'Round {{round}}',
    noPlayer: 'No player',
    noPrompt: 'No prompt ready',
    icebreakerPromptPrivate: 'Prompt is on their device.',
    nextPrompt: 'Next prompt',
    icebreakersSetup: 'Icebreakers setup',
    icebreakersPromptCount: '{{count}} prompts bundled',
    icebreakersRotation: 'Turns rotate evenly before repeating players.',
    quarterMileSetup: 'Quarter Mile setup',
    quarterMileHint: 'Take the known car or gamble on the hidden one.',
    quarterMileKnown: 'Known car',
    quarterMileHidden: 'Hidden car',
    quarterMileTake: 'Take it',
    quarterMileLeave: 'Leave it (take hidden)',
    quarterMileYourGarage: 'Your garage',
    quarterMileScores: 'Garage scores',
    quarterMileWinner: '{{name}} wins the quarter-mile',
    quarterMileWaiting: 'Waiting for {{name}} to choose…',
    quarterMileRevealPair: '{{name}} chose {{choice}}',
    quarterMileChoiceTake: 'the known car',
    quarterMileChoiceLeave: 'the hidden car',
    quarterMileNextPair: 'Next pair',
    mafiosoClue: 'Clue {{n}}: {{clue}}',
    mafiosoCluePrivate: 'Clue is on the host screen.',
    mafiosoTownWins: 'Citizens win — both mafiosos are out.',
    mafiosoMafiaWins: 'Mafiosos win.',
    mafiosoCitizensLeft: '{{count}} citizens still in',
    loadingContentTitle: 'Loading games',
    loadingContentMessage:
      'Getting the latest game rules, questions, and prompts.',
    contentErrorTitle: 'Games could not load',
    contentErrorMessage:
      'Check the connection and try again. Previously loaded games stay cached on this device.',
    contentEmptyTitle: 'No games available',
    contentEmptyMessage:
      'Seed the games collection before hosting a room from this device.',
    retry: 'Try again',
  },
  notifications: {
    title: 'Notifications',
    subtitle: 'Stay in the loop with your people',
    markAllRead: 'Mark all read',
    today: 'Today',
    earlier: 'Earlier',
    emptyTitle: "You're all caught up",
    emptyMessage: 'Invites, RSVPs and updates will appear here.',
  },
  profile: {
    title: 'Profile & Settings',
    subtitle: 'Your events. Your community. Your Lamma.',
    hostedEvents: 'Hosted {{count}} events',
    oneHostedEvent: 'Hosted 1 event',
    joined: 'Joined {{count}}',
    language: 'Language',
    notifications: 'Notifications',
    notificationsHint: 'Event reminders, updates and more',
    appearance: 'Appearance',
    lightMode: 'Light mode',
    darkMode: 'Dark mode',
    myDrafts: 'My drafts',
    myDraftsHint: 'Continue building your events',
    savedThemes: 'Saved themes',
    savedThemesHint: 'Your favorite event ideas',
    help: 'Help & support',
    helpHint: 'FAQs, contact us, and more',
    signOut: 'Sign out',
    signOutHint: 'See you soon!',
    guest: 'Guest',
    upgradePrompt: 'Sign in to save your events',
    editProfileTitle: 'Edit profile',
    displayNameLabel: 'Display name',
    displayNamePlaceholder: 'Your name',
    profileSaved: 'Profile updated',
    upgradeTitle: 'Sign in to Lamma',
    upgradeSubtitle: 'Keep your events, drafts and RSVPs across your devices.',
  },
  language: {
    title: 'Language',
    english: 'English',
    arabic: 'العربية',
    restartHint:
      'The app restarts to apply your language and layout direction.',
  },
  settings: {
    defaultBio: 'Good people. Brighter days.',
    editProfile: 'Edit profile',
    notificationsTitle: 'Notifications',
    remindersLabel: 'Event reminders',
    remindersHint: 'Get reminded before events start',
    rsvpsLabel: 'RSVP updates',
    rsvpsHint: 'When guests respond to your events',
    updatesLabel: 'Event updates',
    updatesHint: 'Posts and changes from hosts',
    invitesLabel: 'New invitations',
    invitesHint: 'When someone invites you',
    appearanceTitle: 'Appearance',
    appearanceHint: 'Choose how Lamma looks',
    light: 'Light mode',
    dark: 'Dark mode',
    system: 'Match system',
    helpTitle: 'Help & support',
    faq: 'Frequently asked questions',
    contactUs: 'Contact us',
    terms: 'Terms of service',
    privacy: 'Privacy policy',
    appVersion: 'Lamma v{{version}}',
    savedThemesTitle: 'Saved themes',
    savedThemesHint: 'Tap the heart to save your favorites',
    savedThemesEmpty: 'No saved themes yet',
  },
};

export type TranslationSchema = typeof en;
