import type { TriviaPack, TriviaQuestion } from '../../core/types';

function l(value: string) {
  return { en: value, ar: value };
}

function q(
  id: string,
  prompt: string,
  options: [string, string, string, string],
  correctIndex: number,
): TriviaQuestion {
  return {
    id,
    prompt: l(prompt),
    options: options.map(l),
    correctIndex,
    packId: 'legacy',
  };
}

export const TRIVIA_PACKS: TriviaPack[] = [
  {
    id: 'general',
    name: l('General Knowledge'),
    questions: [
      q(
        'general-1',
        'Which planet is known as the Red Planet?',
        ['Mars', 'Venus', 'Jupiter', 'Mercury'],
        0,
      ),
      q(
        'general-2',
        'What is the largest ocean on Earth?',
        ['Atlantic Ocean', 'Indian Ocean', 'Pacific Ocean', 'Arctic Ocean'],
        2,
      ),
      q(
        'general-3',
        'How many continents are there?',
        ['Five', 'Six', 'Seven', 'Eight'],
        2,
      ),
      q(
        'general-4',
        'Which gas do plants absorb from the air?',
        ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'],
        1,
      ),
      q(
        'general-5',
        'What is the capital of Japan?',
        ['Kyoto', 'Seoul', 'Tokyo', 'Osaka'],
        2,
      ),
      q(
        'general-6',
        'Which instrument has keys, pedals, and strings?',
        ['Violin', 'Piano', 'Trumpet', 'Drum kit'],
        1,
      ),
      q(
        'general-7',
        'What is the smallest prime number?',
        ['0', '1', '2', '3'],
        2,
      ),
      q(
        'general-8',
        'Which animal is known for changing color?',
        ['Chameleon', 'Kangaroo', 'Penguin', 'Dolphin'],
        0,
      ),
      q(
        'general-9',
        'What do bees collect from flowers?',
        ['Sap', 'Nectar', 'Seeds', 'Bark'],
        1,
      ),
      q(
        'general-10',
        'Which country is shaped like a boot?',
        ['Greece', 'Italy', 'Spain', 'Portugal'],
        1,
      ),
      q(
        'general-11',
        'What is H2O commonly called?',
        ['Salt', 'Water', 'Oxygen', 'Hydrogen'],
        1,
      ),
      q(
        'general-12',
        'Which sport uses a shuttlecock?',
        ['Tennis', 'Squash', 'Badminton', 'Table tennis'],
        2,
      ),
      q(
        'general-13',
        'How many sides does a hexagon have?',
        ['Five', 'Six', 'Seven', 'Eight'],
        1,
      ),
      q(
        'general-14',
        'What is the fastest land animal?',
        ['Lion', 'Cheetah', 'Horse', 'Gazelle'],
        1,
      ),
      q(
        'general-15',
        'Which month has leap day?',
        ['January', 'February', 'March', 'December'],
        1,
      ),
      q(
        'general-16',
        'What is the main language of Brazil?',
        ['Spanish', 'Portuguese', 'French', 'Italian'],
        1,
      ),
      q(
        'general-17',
        'Which star is closest to Earth?',
        ['Sirius', 'Polaris', 'The Sun', 'Betelgeuse'],
        2,
      ),
      q(
        'general-18',
        'What do you call molten rock above ground?',
        ['Magma', 'Lava', 'Granite', 'Basalt'],
        1,
      ),
      q(
        'general-19',
        'Which organ pumps blood?',
        ['Liver', 'Brain', 'Heart', 'Lung'],
        2,
      ),
      q(
        'general-20',
        'What is the tallest type of grass?',
        ['Bamboo', 'Wheat', 'Reed', 'Sugarcane'],
        0,
      ),
      q(
        'general-21',
        'Which metal is liquid at room temperature?',
        ['Mercury', 'Copper', 'Aluminum', 'Silver'],
        0,
      ),
      q(
        'general-22',
        'What is the opposite of nocturnal?',
        ['Solar', 'Diurnal', 'Seasonal', 'Migratory'],
        1,
      ),
      q(
        'general-23',
        'Which bird is a universal peace symbol?',
        ['Eagle', 'Dove', 'Swan', 'Falcon'],
        1,
      ),
      q(
        'general-24',
        'What is the largest mammal?',
        ['Elephant', 'Blue whale', 'Giraffe', 'Hippopotamus'],
        1,
      ),
      q(
        'general-25',
        'Which color is made from red and blue?',
        ['Green', 'Orange', 'Purple', 'Yellow'],
        2,
      ),
      q(
        'general-26',
        'How many minutes are in an hour?',
        ['45', '50', '60', '90'],
        2,
      ),
      q(
        'general-27',
        'Which shape has three sides?',
        ['Square', 'Triangle', 'Pentagon', 'Circle'],
        1,
      ),
      q(
        'general-28',
        'What is the freezing point of water in Celsius?',
        ['0', '10', '32', '100'],
        0,
      ),
      q(
        'general-29',
        'Which device measures temperature?',
        ['Barometer', 'Thermometer', 'Compass', 'Altimeter'],
        1,
      ),
      q(
        'general-30',
        'What is the currency of the United States?',
        ['Dollar', 'Euro', 'Pound', 'Peso'],
        0,
      ),
    ],
  },
  {
    id: 'movies-tv',
    name: l('Movies & TV'),
    questions: [
      q(
        'movies-tv-1',
        'Which movie series features a young wizard named Harry?',
        [
          'The Hunger Games',
          'Harry Potter',
          'The Maze Runner',
          'Percy Jackson',
        ],
        1,
      ),
      q(
        'movies-tv-2',
        'What color is Shrek?',
        ['Blue', 'Green', 'Purple', 'Orange'],
        1,
      ),
      q(
        'movies-tv-3',
        'Which superhero is famous for carrying a shield?',
        ['Captain America', 'Iron Man', 'Thor', 'Aquaman'],
        0,
      ),
      q(
        'movies-tv-4',
        "What is the name of Simba's father?",
        ['Scar', 'Mufasa', 'Timon', 'Rafiki'],
        1,
      ),
      q(
        'movies-tv-5',
        'Which Disney film features the song Let It Go?',
        ['Moana', 'Frozen', 'Tangled', 'Brave'],
        1,
      ),
      q(
        'movies-tv-6',
        'Which sitcom is set partly in Central Perk?',
        ['Friends', 'Seinfeld', 'Frasier', 'Modern Family'],
        0,
      ),
      q(
        'movies-tv-7',
        'Which movie features a DeLorean time machine?',
        ['Back to the Future', 'Ghostbusters', 'E.T.', 'The Goonies'],
        0,
      ),
      q(
        'movies-tv-8',
        'Who lives in a pineapple under the sea?',
        ['Patrick Star', 'SpongeBob SquarePants', 'Squidward', 'Mr. Krabs'],
        1,
      ),
      q(
        'movies-tv-9',
        'Which franchise is known for lightsabers?',
        ['Star Trek', 'Star Wars', 'Dune', 'Avatar'],
        1,
      ),
      q(
        'movies-tv-10',
        "What is Batman's city called?",
        ['Metropolis', 'Gotham City', 'Star City', 'Central City'],
        1,
      ),
      q(
        'movies-tv-11',
        'Which movie series has toys that come alive?',
        ['Toy Story', 'Cars', 'Monsters, Inc.', 'Finding Nemo'],
        0,
      ),
      q(
        'movies-tv-12',
        'Who is the main green ogre in Shrek?',
        ['Farquaad', 'Donkey', 'Shrek', 'Puss in Boots'],
        2,
      ),
      q(
        'movies-tv-13',
        'Which TV family is famously yellow?',
        [
          'The Simpsons',
          'The Addams Family',
          'The Brady Bunch',
          'The Flintstones',
        ],
        0,
      ),
      q(
        'movies-tv-14',
        'What is the central object in The Lord of the Rings?',
        ['A wand', 'A ring', 'A sword', 'A crown'],
        1,
      ),
      q(
        'movies-tv-15',
        'Which film tells a romance set around the Titanic disaster?',
        ['Pearl Harbor', 'Titanic', 'Australia', 'The Notebook'],
        1,
      ),
      q(
        'movies-tv-16',
        'Who says To infinity and beyond?',
        ['Woody', 'Buzz Lightyear', 'Mr. Potato Head', 'Rex'],
        1,
      ),
      q(
        'movies-tv-17',
        'Which story features a glass slipper?',
        ['Cinderella', 'Snow White', 'Mulan', 'Aladdin'],
        0,
      ),
      q(
        'movies-tv-18',
        "What is Spider-Man's first name?",
        ['Bruce', 'Clark', 'Peter', 'Tony'],
        2,
      ),
      q(
        'movies-tv-19',
        'Which show follows doctors at Grey Sloan Memorial?',
        ['House', 'ER', "Grey's Anatomy", 'Scrubs'],
        2,
      ),
      q(
        'movies-tv-20',
        'What is the wizarding school in Harry Potter called?',
        ['Hogwarts', 'Beauxbatons', 'Durmstrang', 'Ilvermorny'],
        0,
      ),
      q(
        'movies-tv-21',
        'Which movie features personified emotions named Joy and Sadness?',
        ['Soul', 'Inside Out', 'Up', 'Coco'],
        1,
      ),
      q(
        'movies-tv-22',
        'Who is the snowman in Frozen?',
        ['Olaf', 'Sven', 'Kristoff', 'Hans'],
        0,
      ),
      q(
        'movies-tv-23',
        'Which city is Home Alone 2 mostly set in?',
        ['Chicago', 'New York City', 'Boston', 'Los Angeles'],
        1,
      ),
      q(
        'movies-tv-24',
        'In The Matrix, which color pill does Neo choose?',
        ['Blue', 'Red', 'Green', 'White'],
        1,
      ),
      q(
        'movies-tv-25',
        'Which film series has a pirate named Jack Sparrow?',
        ['Pirates of the Caribbean', 'Treasure Planet', 'Peter Pan', 'Hook'],
        0,
      ),
      q(
        'movies-tv-26',
        'Who trains Luke Skywalker on Dagobah?',
        ['Obi-Wan Kenobi', 'Yoda', 'Mace Windu', 'Qui-Gon Jinn'],
        1,
      ),
      q(
        'movies-tv-27',
        'Which sitcom has a character named Sheldon Cooper?',
        [
          'The Office',
          'The Big Bang Theory',
          'Community',
          'Parks and Recreation',
        ],
        1,
      ),
      q(
        'movies-tv-28',
        "What is the name of Black Panther's country?",
        ['Genovia', 'Wakanda', 'Latveria', 'Zamunda'],
        1,
      ),
      q(
        'movies-tv-29',
        'Which film includes the phrase Hakuna Matata?',
        ['The Lion King', 'Tarzan', 'Madagascar', 'Rio'],
        0,
      ),
      q(
        'movies-tv-30',
        'What movie has a clownfish named Nemo?',
        ['Shark Tale', 'Finding Nemo', 'The Little Mermaid', 'Luca'],
        1,
      ),
    ],
  },
  {
    id: 'sports',
    name: l('Sports'),
    questions: [
      q(
        'sports-1',
        'How many players start on the field for one association football team?',
        ['9', '10', '11', '12'],
        2,
      ),
      q(
        'sports-2',
        'Which sport uses a racket, a net, and a felt-covered ball?',
        ['Tennis', 'Cricket', 'Hockey', 'Baseball'],
        0,
      ),
      q(
        'sports-3',
        'In American football, what is a touchdown worth before the kick?',
        ['3 points', '5 points', '6 points', '7 points'],
        2,
      ),
      q(
        'sports-4',
        'Which sport is divided into innings?',
        ['Baseball', 'Basketball', 'Rugby', 'Swimming'],
        0,
      ),
      q(
        'sports-5',
        'How many rings are on the Olympic flag?',
        ['Four', 'Five', 'Six', 'Seven'],
        1,
      ),
      q(
        'sports-6',
        'What sport uses a puck?',
        ['Ice hockey', 'Golf', 'Volleyball', 'Handball'],
        0,
      ),
      q(
        'sports-7',
        'Which race is 42.195 kilometers?',
        ['10K', 'Half marathon', 'Marathon', 'Triathlon sprint'],
        2,
      ),
      q(
        'sports-8',
        'What is the famous tennis tournament held in London?',
        ['Roland-Garros', 'Wimbledon', 'US Open', 'Australian Open'],
        1,
      ),
      q(
        'sports-9',
        'Which sport features a scrum?',
        ['Rugby', 'Badminton', 'Fencing', 'Cycling'],
        0,
      ),
      q(
        'sports-10',
        'How many points is a basketball free throw worth?',
        ['1', '2', '3', '4'],
        0,
      ),
      q(
        'sports-11',
        'What is a hat trick usually?',
        [
          'Three scores by one player',
          'A penalty kick',
          'A tiebreak',
          'A defensive save',
        ],
        0,
      ),
      q(
        'sports-12',
        'Which sport uses a pommel horse?',
        ['Gymnastics', 'Polo', 'Equestrian jumping', 'Boxing'],
        0,
      ),
      q(
        'sports-13',
        'How many players are on one side in indoor volleyball?',
        ['5', '6', '7', '8'],
        1,
      ),
      q(
        'sports-14',
        'The FIFA World Cup is awarded in which sport?',
        ['Cricket', 'Football', 'Rugby', 'Basketball'],
        1,
      ),
      q(
        'sports-15',
        'Which sport uses clubs and holes?',
        ['Golf', 'Lacrosse', 'Hockey', 'Curling'],
        0,
      ),
      q(
        'sports-16',
        'In football, where can the goalkeeper handle the ball?',
        ['Center circle', 'Penalty area', 'Touchline', 'Anywhere'],
        1,
      ),
      q(
        'sports-17',
        'Which combat sport awards ippon?',
        ['Judo', 'Boxing', 'Wrestling', 'Taekwondo'],
        0,
      ),
      q(
        'sports-18',
        'How many bases are on a baseball field?',
        ['3', '4', '5', '6'],
        1,
      ),
      q(
        'sports-19',
        'Which sport awards a yellow jersey at the Tour de France?',
        ['Running', 'Cycling', 'Skiing', 'Rowing'],
        1,
      ),
      q(
        'sports-20',
        'What does NBA stand for?',
        [
          'National Basketball Association',
          'North Basketball Alliance',
          'New Basketball Agency',
          'National Boxing Association',
        ],
        0,
      ),
      q(
        'sports-21',
        'Which sport uses a shuttlecock?',
        ['Badminton', 'Padel', 'Squash', 'Tennis'],
        0,
      ),
      q(
        'sports-22',
        'How long is a standard professional football match before stoppage time?',
        ['60 minutes', '75 minutes', '90 minutes', '100 minutes'],
        2,
      ),
      q(
        'sports-23',
        'In tennis, what does winning all four majors in one year make?',
        ['Triple crown', 'Grand slam', 'Clean sweep', 'Golden set'],
        1,
      ),
      q(
        'sports-24',
        'Which sport has a goalie crease?',
        ['Ice hockey', 'Baseball', 'Archery', 'Table tennis'],
        0,
      ),
      q(
        'sports-25',
        'Formula 1 is raced with what?',
        ['Motorcycles', 'Open-wheel cars', 'Boats', 'Rally trucks'],
        1,
      ),
      q(
        'sports-26',
        'How many players from one basketball team are on court?',
        ['4', '5', '6', '7'],
        1,
      ),
      q(
        'sports-27',
        'Which surface is most associated with Roland-Garros?',
        ['Grass', 'Clay', 'Hard court', 'Carpet'],
        1,
      ),
      q(
        'sports-28',
        'In golf, what is a birdie?',
        ['One under par', 'One over par', 'Two under par', 'A lost ball'],
        0,
      ),
      q(
        'sports-29',
        'Which country hosted the first modern Olympic Games?',
        ['France', 'Greece', 'United States', 'Italy'],
        1,
      ),
      q(
        'sports-30',
        'A triathlon combines swimming, cycling, and what else?',
        ['Skiing', 'Running', 'Rowing', 'Climbing'],
        1,
      ),
    ],
  },
  {
    id: 'egypt-arabic',
    name: l('Egypt & Arabic'),
    questions: [
      q(
        'egypt-arabic-1',
        'What river runs through Cairo?',
        ['Nile', 'Amazon', 'Danube', 'Tigris'],
        0,
      ),
      q(
        'egypt-arabic-2',
        'Which sea borders Egypt to the north?',
        ['Red Sea', 'Mediterranean Sea', 'Arabian Sea', 'Dead Sea'],
        1,
      ),
      q(
        'egypt-arabic-3',
        'What is the capital of Egypt?',
        ['Alexandria', 'Giza', 'Cairo', 'Luxor'],
        2,
      ),
      q(
        'egypt-arabic-4',
        'Which ancient writing used pictorial symbols?',
        ['Cuneiform', 'Latin', 'Hieroglyphs', 'Runes'],
        2,
      ),
      q(
        'egypt-arabic-5',
        'What does shukran mean in Arabic?',
        ['Please', 'Thank you', 'Goodbye', 'Welcome'],
        1,
      ),
      q(
        'egypt-arabic-6',
        'Which city is famous for Bibliotheca Alexandrina?',
        ['Aswan', 'Alexandria', 'Port Said', 'Mansoura'],
        1,
      ),
      q(
        'egypt-arabic-7',
        'What is koshari?',
        ['A dessert', 'A popular Egyptian dish', 'A dance', 'A river boat'],
        1,
      ),
      q(
        'egypt-arabic-8',
        'Which desert lies west of the Nile Valley?',
        ['Eastern Desert', 'Western Desert', 'Sinai Desert', 'Negev Desert'],
        1,
      ),
      q(
        'egypt-arabic-9',
        'What is the currency of Egypt?',
        [
          'Egyptian pound',
          'Egyptian dinar',
          'Egyptian dirham',
          'Egyptian rial',
        ],
        0,
      ),
      q(
        'egypt-arabic-10',
        'Which governorate includes the Pyramids of Giza?',
        ['Cairo', 'Giza', 'Luxor', 'Aswan'],
        1,
      ),
      q(
        'egypt-arabic-11',
        'What does ahlan mean?',
        ['Hello', 'Tomorrow', 'Water', 'Friend'],
        0,
      ),
      q(
        'egypt-arabic-12',
        'Which sea borders Sinai to the east?',
        ['Red Sea', 'Mediterranean Sea', 'Caspian Sea', 'Black Sea'],
        0,
      ),
      q(
        'egypt-arabic-13',
        'What is the traditional Egyptian spring holiday?',
        ['Eid al-Fitr', 'Sham El-Nessim', 'Moulid', 'Ashura'],
        1,
      ),
      q(
        'egypt-arabic-14',
        'Which Egyptian city is known for the Karnak Temple complex?',
        ['Luxor', 'Suez', 'Tanta', 'Damietta'],
        0,
      ),
      q(
        'egypt-arabic-15',
        'What is ful medames mainly made from?',
        ['Lentils', 'Fava beans', 'Chickpeas', 'Rice'],
        1,
      ),
      q(
        'egypt-arabic-16',
        'Arabic is commonly written in which direction?',
        ['Left to right', 'Right to left', 'Top to bottom', 'Bottom to top'],
        1,
      ),
      q(
        'egypt-arabic-17',
        'What does kitab mean in Arabic?',
        ['Book', 'House', 'Street', 'Coffee'],
        0,
      ),
      q(
        'egypt-arabic-18',
        'Which city sits at the northern entrance of the Suez Canal?',
        ['Port Said', 'Hurghada', 'Minya', 'Fayoum'],
        0,
      ),
      q(
        'egypt-arabic-19',
        'What is a felucca?',
        ['A sailboat', 'A drum', 'A bread', 'A market'],
        0,
      ),
      q(
        'egypt-arabic-20',
        'Which month is known for fasting in Islam?',
        ['Shaaban', 'Ramadan', 'Muharram', 'Rajab'],
        1,
      ),
      q(
        'egypt-arabic-21',
        'What is molokhia?',
        [
          'A leafy green dish',
          'A sweet pastry',
          'A coffee style',
          'A spice mix',
        ],
        0,
      ),
      q(
        'egypt-arabic-22',
        'Which Egyptian singer is known as the Star of the East?',
        ['Umm Kulthum', 'Dalida', 'Fairuz', 'Warda'],
        0,
      ),
      q(
        'egypt-arabic-23',
        'What does yalla usually mean?',
        ['Come on', 'Good night', 'Thank you', 'Excuse me'],
        0,
      ),
      q(
        'egypt-arabic-24',
        'Which Red Sea resort city is famous for diving?',
        ['Hurghada', 'Damanhur', 'Qena', 'Beni Suef'],
        0,
      ),
      q(
        'egypt-arabic-25',
        'What does as-salamu alaykum mean?',
        [
          'Peace be upon you',
          'See you later',
          'I am hungry',
          'What time is it',
        ],
        0,
      ),
      q(
        'egypt-arabic-26',
        "Which ancient queen ruled Egypt in Julius Caesar's era?",
        ['Hatshepsut', 'Cleopatra VII', 'Nefertiti', 'Sobekneferu'],
        1,
      ),
      q(
        'egypt-arabic-27',
        'What is a galabeya?',
        ['A traditional robe', 'A soup', 'A musical instrument', 'A festival'],
        0,
      ),
      q(
        'egypt-arabic-28',
        'Which city is near the Valley of the Kings?',
        ['Luxor', 'Suez', 'Rosetta', 'Ismailia'],
        0,
      ),
      q(
        'egypt-arabic-29',
        'What is the common Egyptian Arabic word for bread?',
        ['Aish', 'Laban', 'Maya', 'Shay'],
        0,
      ),
      q(
        'egypt-arabic-30',
        'Which canal connects the Mediterranean and Red Sea?',
        ['Panama Canal', 'Suez Canal', 'Corinth Canal', 'Kiel Canal'],
        1,
      ),
    ],
  },
];
